In [31]:
from pathlib import Path
import pandas as pd
import os
from os import listdir
import random
import datetime
from os import listdir
from os.path import join as jp

import numpy as np
import pandas as pd
from pandas import DataFrame
from pandas import Series
import matplotlib.pyplot as plt
from math import radians, degrees, sin, cos, asin, acos, sqrt
import haversine
# import tensorflow

# from keras.models import Sequential
# from keras.layers import Dense, Input, Activation, BatchNormalization, Dropout

from sklearn import metrics
from sklearn.cluster import DBSCAN
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

pd.options.mode.chained_assignment = None

In [2]:
wdir = os.path.join(os.getcwd(),'cabspottingdata')
file_names = [f for f in listdir(wdir)]
# file_names = file_names[:200]
data = pd.DataFrame()
# # file_names=['new_abboip.txt', 'new_abcoij.txt']
for file in file_names:
    temp = pd.read_csv(os.path.join(wdir, file), sep=" ", header=None)
    temp['cab_name'] = file.split('.')[0]
    data=data.append(temp, ignore_index=True)
data.columns = ['latitude', 'longitude', 'occupancy', 'time', 'cab_name']
data.head()

   latitude  longitude  occupancy        time    cab_name
0  37.75153 -122.39447          0  1211033530  new_abboip
1  37.75149 -122.39447          0  1211033614  new_abboip
2  37.75149 -122.39447          0  1211033674  new_abboip
3  37.75149 -122.39446          0  1211033735  new_abboip
4  37.75144 -122.39449          0  1211035303  new_abboip

In [3]:
data['cab_name'].nunique()

537

In [4]:
data.describe()

           latitude     longitude     occupancy          time
count  1.122006e+07  1.122006e+07  1.122006e+07  1.122006e+07
mean   3.776360e+01 -1.224124e+02  4.472238e-01  1.212036e+09
std    5.385999e-02  3.578201e-02  4.972069e-01  5.885683e+05
min    3.286970e+01 -1.270814e+02  0.000000e+00  1.211018e+09
25%    3.775513e+01 -1.224253e+02  0.000000e+00  1.211523e+09
50%    3.778106e+01 -1.224111e+02  0.000000e+00  1.212043e+09
75%    3.779045e+01 -1.224003e+02  1.000000e+00  1.212549e+09
max    5.030546e+01 -1.155622e+02  1.000000e+00  1.213090e+09

In [5]:
data.shape

(11220058, 5)

In [51]:
# from pandas_profiling import ProfileReport
# # EDA analysis
# profile = ProfileReport(data, title='Cab spotting Report', explorative=True)
# profile.to_widgets()
# profile.to_file("CabSpottingEDA.html")

Summarize dataset:   0%|          | 0/18 [00:00<?, ?it/s]

C:\Users\svi02\Anaconda3\lib\site-packages\scipy\stats\stats.py:4594: RuntimeWarning: overflow encountered in longlong_scalars
  (2 * xtie * ytie) / m + x0 * y0 / (9 * m * (size - 2)))

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render widgets:   0%|          | 0/1 [00:00<?, ?it/s]

VBox(children=(Tab(children=(Tab(children=(GridBox(children=(VBox(children=(GridspecLayout(children=(HTML(valu…

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

In [18]:
data.groupby(by='cab_name').count().sort_values("occupancy", ascending=True)

              latitude  longitude  occupancy   time
cab_name
new_eotcue          59         59         59     59
new_mfeuer         103        103        103    103
new_egoiwroi       185        185        185    185
new_oilrag         932        932        932    932
new_ifeshce       1003       1003       1003   1003
...                ...        ...        ...    ...
new_ejshigib     29536      29536      29536  29536
new_enkkand      29742      29742      29742  29742
new_equioc       29997      29997      29997  29997
new_udwadla      33753      33753      33753  33753
new_upthin       49367      49367      49367  49367

[537 rows x 4 columns]

In [13]:
import datetime as dt
dt.datetime.fromtimestamp(data.loc[data['cab_name'] =='new_eotcue', ['time']].values[0][0]).strftime('%Y-%m-%d %H:%M:%S')

'2008-05-22 16:33:48'

In [15]:
# data['timestamp']=
dt.datetime.fromtimestamp(data.loc[data['cab_name'] =='new_eotcue', ['time']]).strftime('%Y-%m-%d %H:%M:%S')

TypeError: an integer is required (got type DataFrame)

In [23]:
data['timestamp']=data['time'].apply(lambda x: dt.datetime.fromtimestamp(x).strftime('%Y-%m-%d %H:%M:%S'))
data.loc[data['cab_name'] =='new_eotcue']

,latitude,longitude,occupancy,time,cab_name,timestamp
4216711,37.75010,-122.39377,0,1211466828,new_eotcue,2008-05-22 16:33:48
4216712,37.75010,-122.39377,0,1211490788,new_eotcue,2008-05-22 23:13:08
4216713,37.75039,-122.39344,0,1212292269,new_eotcue,2008-06-01 05:51:09
4216714,37.75147,-122.39534,0,1212292331,new_eotcue,2008-06-01 05:52:11
4216715,37.75129,-122.39537,0,1212292381,new_eotcue,2008-06-01 05:53:01
4216716,37.75143,-122.39533,0,1212292441,new_eotcue,2008-06-01 05:54:01
4216717,37.75142,-122.39533,0,1212292501,new_eotcue,2008-06-01 05:55:01
4216718,37.75140,-122.39530,0,1212292566,new_eotcue,2008-06-01 05:56:06
4216719,37.75140,-122.39530,0,1212292621,new_eotcue,2008-06-01 05:57:01
4216720,37.74983,-122.39630,0,1212292681,new_eotcue,2008-06-01 05:58:01
4216721,37.74948,-122.40180,0,1212292741,new_eotcue,2008-06-01 05:59:01
4216722,37.74839,-122.40925,0,1212292817,new_eotcue,2008-06-01 06:00:17
4216723,37.74837,-122.41253,0,1212292867,new_eotcue,2008-06-01 06:01:07
4216724,37.74826,-122.41793,0,1212292924,new_eotcue,2008-06-01 06:02:04
4216725,37.74892,-122.42041,0,1212292987,new_eotcue,2008-06-01 06:03:07
4216726,37.75230,-122.42064,0,1212293049,new_eotcue,2008-06-01 06:04:09
4216727,37.75528,-122.42095,0,1212293102,new_eotcue,2008-06-01 06:05:02
4216728,37.75528,-122.42095,0,1212293117,new_eotcue,2008-06-01 06:05:17
4216729,37.75851,-122.42128,0,1212293163,new_eotcue,2008-06-01 06:06:03
4216730,37.76285,-122.42165,0,1212293223,new_eotcue,2008-06-01 06:07:03
4216731,37.76471,-122.42188,0,1212293288,new_eotcue,2008-06-01 06:08:08
4216732,37.76572,-122.42191,0,1212293403,new_eotcue,2008-06-01 06:10:03
4216733,37.76576,-122.42192,0,1212293471,new_eotcue,2008-06-01 06:11:11
4216734,37.76577,-122.42189,0,1212293523,new_eotcue,2008-06-01 06:12:03
4216735,37.76577,-122.42189,0,1212293584,new_eotcue,2008-06-01 06:13:04
4216736,37.76641,-122.42209,0,1212293644,new_eotcue,2008-06-01 06:14:04
4216737,37.76641,-122.42209,0,1212293680,new_eotcue,2008-06-01 06:14:40
4216738,37.76644,-122.42418,0,1212293705,new_eotcue,2008-06-01 06:15:05
4216739,37.76467,-122.42416,0,1212293769,new_eotcue,2008-06-01 06:16:09
4216740,37.76326,-122.42196,0,1212293826,new_eotcue,2008-06-01 06:17:06
4216741,37.76446,-122.42182,0,1212293891,new_eotcue,2008-06-01 06:18:11
4216742,37.76491,-122.42392,0,1212293945,new_eotcue,2008-06-01 06:19:05
4216743,37.76487,-122.42391,1,1212293963,new_eotcue,2008-06-01 06:19:23
4216744,37.76486,-122.42396,1,1212294022,new_eotcue,2008-06-01 06:20:22
4216745,37.76741,-122.42433,1,1212294082,new_eotcue,2008-06-01 06:21:22
4216746,37.76829,-122.42029,1,1212294149,new_eotcue,2008-06-01 06:22:29
4216747,37.76887,-122.41779,1,1212294208,new_eotcue,2008-06-01 06:23:28
4216748,37.77094,-122.41518,1,1212294264,new_eotcue,2008-06-01 06:24:24
4216749,37.77134,-122.41455,1,1212294297,new_eotcue,2008-06-01 06:24:57
4216750,37.77134,-122.41459,1,1212294325,new_eotcue,2008-06-01 06:25:25
4216751,37.77135,-122.41459,0,1212294327,new_eotcue,2008-06-01 06:25:27
4216752,37.77166,-122.41424,1,1212294342,new_eotcue,2008-06-01 06:25:42
4216753,37.77368,-122.41177,1,1212294402,new_eotcue,2008-06-01 06:26:42
4216754,37.77659,-122.40802,1,1212294462,new_eotcue,2008-06-01 06:27:42
4216755,37.77659,-122.40802,1,1212294474,new_eotcue,2008-06-01 06:27:54
4216756,37.77701,-122.40382,1,1212294526,new_eotcue,2008-06-01 06:28:46
4216757,37.77701,-122.40382,1,1212294541,new_eotcue,2008-06-01 06:29:01
4216758,37.77314,-122.39932,1,1212294582,new_eotcue,2008-06-01 06:29:42
4216759,37.76278,-122.39287,1,1212294642,new_eotcue,2008-06-01 06:30:42
4216760,37.75265,-122.39276,1,1212294702,new_eotcue,2008-06-01 06:31:42
4216761,37.75165,-122.39359,1,1212294762,new_eotcue,2008-06-01 06:32:42
4216762,37.75157,-122.39536,1,1212294822,new_eotcue,2008-06-01 06:33:42
4216763,37.75162,-122.39542,1,1212294882,new_eotcue,2008-06-01 06:34:42
4216764,37.75167,-122.39548,1,1212294953,new_eotcue,2008-06-01 06:35:53
4216765,37.75132,-122.39537,1,1212295009,new_eotcue,2008-06-01 06:36:49
4216766,37.75132,-122.39537,1,1212295036,new_eotcue,2008-06-01 06:37:16
4216767,37.75124,-122.39521,1,1212295091,new_eotcue,2008-06-01 06:38:11
4216768,37.75136,-122.39500,1,1212295114,new_eotcue,2008-06-01 06:38:34
4216769,37.75136,-122.39500,0,1212295118,new_eotcue,2008-06-01 06:38:38

In [32]:
import haversine

def PreviousCoordinates(df):
    df['prevlatitude'] = df.shift(1)['latitude']
    df['prevlongitude'] = df.shift(1)['longitude']
    df = df.dropna()
    return df

def EstimatedDistance(row):
    # formulation of finding distance via longitude and latitude in Miles from
    # https://gist.github.com/rochacbruno/2883505#gistcomment-1394026
    Longitude = row['longitude']
    Latitude = row['latitude']
    PrevLongitude = row['prevlongitude']
    PrevLatitude = row['prevlatitude']
    Longitude, Latitude, PrevLongitude, PrevLatitude = map(radians, 
                                                                    [Longitude, Latitude, 
                                                                    PrevLongitude, PrevLatitude])
    try:
        return 6371  * (acos(sin(Latitude) * sin(PrevLatitude) + cos(Latitude) * cos(PrevLatitude) * 
                                cos(Longitude - PrevLongitude)))
    except:
        return 0.0

def DistanceCalculation(df):
    df['kms'] = 0.0
    df['kms'] = df.apply(lambda row: EstimatedDistance(row), axis=1)
    return df

data=PreviousCoordinates(df=data)
data=DistanceCalculation(df=data)
data.head()
# Data = pd.DataFrame()
# for f in SelectedFiles:
#     df = ConverttoDF(file_name=f)
#     df = PreviousCoordinates(df=df)
#     df = DistanceCalculation(df=df)
#     Data = pd.concat([Data, df])

,latitude,longitude,occupancy,time,cab_name,timestamp,prevlatitude,prevlongitude,kms
2,37.75149,-122.39447,0,1211033674,new_abboip,2008-05-17 16:14:34,37.75149,-122.39447,0.000000
3,37.75149,-122.39446,0,1211033735,new_abboip,2008-05-17 16:15:35,37.75149,-122.39447,0.000880
4,37.75144,-122.39449,0,1211035303,new_abboip,2008-05-17 16:41:43,37.75149,-122.39446,0.006154
5,37.75151,-122.39453,0,1211035374,new_abboip,2008-05-17 16:42:54,37.75144,-122.39449,0.008542
6,37.75137,-122.39502,0,1211035434,new_abboip,2008-05-17 16:43:54,37.75151,-122.39453,0.045807

In [39]:
from haversine import haversine, Unit

lat1 = 37.75149; lat2 = 37.75144; long1 = -122.39446; long2 = -122.39449
print(haversine((lat1, long1), (lat2, long2)) )

0.006153669480742152

In [34]:
!pip install haversine

Collecting haversine
  Downloading haversine-2.3.1-py2.py3-none-any.whl (5.5 kB)
Installing collected packages: haversine
Successfully installed haversine-2.3.1