In [119]:
import pandas as pd
import numpy as np
#from multiscorer import MultiScorer

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
from sklearn.model_selection import cross_val_score
from numpy import average

#scorer = MultiScorer({                                               # Create a MultiScorer instance
#  'accuracy': (accuracy_score, {}),
#  'precision': (precision_score, {'average': 'weighted'}),
#     'recall': (recall_score, {'average': 'weighted'}),
#       'f1': (f1_score, {'average': 'weighted'})
#})

train_data = pd.read_csv("C:\\Users\\svi02\\Downloads\\candidate_data\\train_data.csv" ,
                                header=0)
train_data.describe()

,radius_0,texture_0,perimeter_0,radius_1,texture_1,perimeter_1,radius_2,perimeter_2,age,cancer_type
count,398.000000,398.000000,398.000000,343.000000,398.000000,264.000000,398.000000,398.000000,398.000000,398.000000
mean,21.303711,18.957554,92.128890,14.123575,30.417222,94.086379,14.134922,127.222422,39.876884,0.628141
std,49.987646,6.243499,25.159787,3.780636,15.027855,27.314466,3.748146,49.097558,13.427196,0.483909
min,6.401956,-17.243202,45.612505,5.752395,2.395868,43.444930,7.079847,44.918942,18.000000,0.000000
25%,11.693885,14.581364,74.975361,11.600838,19.898062,75.188880,11.573592,84.123724,28.000000,0.000000
50%,13.468170,18.238742,87.376764,13.385789,30.897762,90.054613,13.333610,129.992697,39.000000,1.000000
75%,16.323024,22.494291,104.876420,16.051640,42.555657,106.085670,16.093900,169.538170,50.000000,1.000000
max,561.311068,40.064462,193.755763,29.645166,55.820612,227.162938,28.563252,214.192377,64.000000,1.000000

In [120]:
test_data = pd.read_csv("C:\\Users\\svi02\\Downloads\\candidate_data\\test_data.csv" ,
                                header=0)

In [121]:
test_data['cancer_type']= pd.read_csv("C:\\Users\\svi02\\Downloads\\candidate_data\\sample_submission.csv" ,
                                header=0)
train_data.head()

,radius_0,texture_0,perimeter_0,radius_1,texture_1,perimeter_1,radius_2,texture_2,perimeter_2,age,treatment_date,diagnose_date,cancer_type
0,19.858394,27.204437,136.324256,22.683290,32.802578,119.523841,21.477052,27.3070874472,82.366936,44,2006-06-03,2005-10-23,0
1,14.182069,15.754730,80.916983,14.043753,30.094704,94.911073,15.012329,17.8551305385,103.078286,59,2004-02-22,2007-08-20,1
2,25.380268,21.291553,152.281062,23.852166,46.237931,NaN,28.563252,21.0971528265,143.367792,37,2006-01-06,2004-08-07,0
3,11.835961,17.820702,72.178523,11.260258,44.805167,NaN,12.082749,16.4992370844,65.920413,51,2003-04-14,2005-06-16,1
4,14.875600,17.534187,98.545830,14.380683,26.190447,89.712492,12.930685,19.8566873539,108.380754,21,2004-06-21,2002-11-27,1

In [122]:
from datetime import datetime, timedelta
# Date type
train_data['treatment_date'] = train_data['treatment_date'].astype('datetime64[ns]')
train_data['diagnose_date'] = train_data['diagnose_date'].astype('datetime64[ns]')
test_data['treatment_date'] = test_data['treatment_date'].astype('datetime64[ns]')
test_data['diagnose_date'] = test_data['diagnose_date'].astype('datetime64[ns]')

# Interval column
train_data['diagonse_interval'] = train_data['treatment_date'] - train_data['diagnose_date']
test_data['diagonse_interval'] = test_data['treatment_date'] - test_data['diagnose_date']

# String
train_data['diagonse_interval'] = train_data['diagonse_interval'].dt.days.astype(int)
test_data['diagonse_interval'] = test_data['diagonse_interval'].dt.days.astype(int)
# train_data['texture_2'] = train_data['texture_2'].astype(float)
# test_data['texture_2'] = test_data['texture_2'].astype(float)

In [123]:
# Using Skicit-learn to split data into training and testing sets
from sklearn.model_selection import train_test_split
# Split the data into training and testing sets
train_features = train_data[train_data.columns[~train_data.columns.isin(['cancer_type', 'diagnose_date', 'treatment_date'])]] 
test_features = test_data[test_data.columns[~test_data.columns.isin(['cancer_type', 'diagnose_date', 'treatment_date'])]] 
train_labels = train_data.iloc[:,-1]
test_labels = test_data.iloc[:,-1]
train_features[train_features.texture_2 =='xx'] = train_features[train_features.texture_2 =='xx'].replace('xx',0)
test_features[test_features.texture_2 =='xx'] = test_features[test_features.texture_2 =='xx'].replace('xx',0)
train_features=train_features.fillna(0)
test_features=test_features.fillna(0)

C:\Anaconda\lib\site-packages\ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

C:\Anaconda\lib\site-packages\pandas\core\indexing.py:537: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[item] = s
C:\Anaconda\lib\site-packages\ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':

In [124]:
# Import the model we are using
from sklearn.ensemble import RandomForestRegressor
# Instantiate model with 1000 decision trees
rf = RandomForestRegressor(n_estimators = 1000, random_state = 42)
# Train the model on training data
rf.fit(train_features, train_labels)

RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
           max_features='auto', max_leaf_nodes=None,
           min_impurity_decrease=0.0, min_impurity_split=None,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators=1000, n_jobs=1,
           oob_score=False, random_state=42, verbose=0, warm_start=False)

In [126]:
from sklearn.metrics import classification_report
predicted = rf.predict(test_features)
report = classification_report(test_labels, predicted)

ValueError: Mix type of y not allowed, got types {'multiclass', 'continuous'}

In [128]:
train_features.dtypes

radius_0             float64
texture_0            float64
perimeter_0          float64
radius_1             float64
texture_1            float64
perimeter_1          float64
radius_2             float64
texture_2             object
perimeter_2          float64
age                    int64
diagonse_interval      int64
dtype: object

In [129]:
test_features.dtypes

radius_0             float64
texture_0            float64
perimeter_0          float64
radius_1             float64
texture_1            float64
perimeter_1          float64
radius_2             float64
texture_2             object
perimeter_2          float64
age                    int64
diagonse_interval      int64
dtype: object