In [1]:
import pandas as pd
df = pd.read_csv("C:\\Users\\svi02\\Documents\\CXL_CLUSTER.CSV" , 
                 sep=';',
                 header=0                    
                   )
df.shape

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa0 in position 0: invalid start byte

In [6]:
df.head()

,HOTEL_ID,HOTEL_NAME,CHAIN INFO,HOTEL_CHAIN_COVERAGE_ID,HOTEL_CHAIN_COVERAGE_NAME,HOTEL_CHAIN_ID,HOTEL_CHAIN_NAME,HOTEL_BRAND_ID,HOTEL_BRAND_NAME,LOCATION INFO,...,AUDIT_TOTAL_AVAILABILITY_CASES,AUDIT_SHARE_RATE_CORRECTNESS,AUDIT_PRICE_POINTS,AUDIT_RATE_CORRECTNESS_AND_AVAILABILITY,AUDIT_RATE_INCORRECTNESS_AND_AVAILABILITY,SHARE_RATE_INCORRECTNESS,SHARE_PRICE_CORRECTNESS,Sourcing stats 2018,Destination RNs spelled out 2018,Invitations 2018
0,1,Savoy Berlin,NaN,2,Regional,237,WorldHotels,237,WorldHotels,NaN,...,390.0,0.9933,149.0,148.0,1.0,0.0067,0.9933,NaN,NaN,NaN
1,2,Berlin Plaza Am Kurfürstendamm,NaN,0,Individual,-1,individual,-1,n.a.,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,Wyndham Excelsior,NaN,0,Individual,-1,individual,-1,n.a.,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,ibis Berlin Messe,NaN,1,Global,550,Accor,1464,IBIS Standard,NaN,...,126.0,1.0000,84.0,84.0,0.0,0.0000,1.0000,NaN,NaN,NaN
4,5,Mercure Airport Hotel Berlin Tegel,NaN,1,Global,550,Accor,1461,Mercure by Accor,NaN,...,570.0,0.9801,452.0,443.0,9.0,0.0199,0.9801,NaN,NaN,NaN

In [7]:
df = df.dropna(axis='columns')

In [9]:
df.head()

,HOTEL_ID,HOTEL_CHAIN_COVERAGE_ID,HOTEL_CHAIN_COVERAGE_NAME,HOTEL_CHAIN_ID,HOTEL_CHAIN_NAME,HOTEL_BRAND_ID,HOTEL_BRAND_NAME,HOTEL_CITY_ID,HOTEL_CITY_NAME,HOTEL_COUNTRY_ID,HOTEL_COUNTRY_NAME,HOTEL_CATEGORY_SHORT_DESC,CONTRACTINGSALESAREA,IS_COVERED,CONTRACT_STATUS,HOTEL_STATUS
0,1,2,Regional,237,WorldHotels,237,WorldHotels,55133,Berlin,33,Germany,4*,Germany Berlin Dresden,YES,free sale,open
1,2,0,Individual,-1,individual,-1,n.a.,55133,Berlin,33,Germany,3*,Germany Berlin Dresden,NO,rejection,open
2,3,0,Individual,-1,individual,-1,n.a.,55133,Berlin,33,Germany,4*,Germany Berlin Dresden,NO,no contract,open
3,4,1,Global,550,Accor,1464,IBIS Standard,55133,Berlin,33,Germany,2*,Germany Berlin Dresden,YES,CRS connection,open
4,5,1,Global,550,Accor,1461,Mercure by Accor,55133,Berlin,33,Germany,4*,Germany Berlin Baltic,YES,CRS connection,open

In [14]:
df_sub = df.head(300000)

In [15]:
df_sub.to_csv('C:\\Users\\svi02\\Downloads\\Hotel_content_report_test.csv', 
          sep = ',', 
          header = True,
          encoding='utf-8',
          index=False)

In [16]:
import os
file_size = os.path.getsize("C:\\Users\\svi02\\Downloads\\Hotel_content_report_test.csv")
file_size = file_size/(1024*1024.0)
file_size

37.798855781555176