In [5]:
import pandas as pd

df_1 = pd.read_excel('C:/Users/svi02/Documents/misc/TargetVSOffer_rates_hotels.xlsx',
                       sheet_name='Target_rates_wo_outliers', 
                       encoding='utf-8')
df_1.head()

,HOTEL_ID,HOTEL_NAME,RFP_ID,RFP_NAME,RFP_SEASON,RATE_TYPE,BREAKFAST_TYPE,TARGET_RATE,TARGET_RATE_CURRENCY,MARKET_PLACE_HOTEL_STATUS,...,RFP_CREATION_DATE,CURRENCY_ISO,CURRENCY_EXCHANGE_RATE_DATE,CURRENCY_EXCHANGE_RATE,TARGET_RATE_EUR,RFP_OFFER_TIMESTAMP,OFFER_RATE,Deviation,OUTLIER,Blind Bid
0,943921,Focus Poznań,9604c35e-9c92-404e-b901-4af758d68338,BRIDGESTONE EUROPE RFP 2019,2019,LRA,INCLUDED,48.0,PLN,SIGNED_UP,...,2018-08-14,PLN,2018-08-14,4.30266,11.155890,2018-11-14 15:39:49,46.322,3.152246,N,NaN
1,5626,Brunelleschi,bdf515b3-e647-4a14-8a81-00dbee2de486,Wind TRE RFP 2019,2019,LRA,INCLUDED,137.0,EUR,SIGNED_UP,...,2018-10-31,EUR,2018-10-31,1.00000,137.000000,2018-11-29 17:09:21,534.000,2.897810,N,NaN
2,441473,Park Inn By Radisson Manchester City Centre,ef3cb088-9445-48e9-8af0-e62e144f3f5e,Hitachi RFP 2019,2019,LRA,INCLUDED,88.0,GBP,SIGNED_UP,...,2018-08-30,GBP,2018-08-30,0.89750,98.050139,2018-10-19 16:13:11,373.698,2.811295,N,NaN
3,67675,Shiba Park Hotel,9a3501c3-814d-11e8-81f1-005056a93fbf,World Bank Transient RFP 2019,2019,LRA,INCLUDED,17181.0,JPY,SIGNED_UP,...,2018-07-06,JPY,2018-07-06,129.62249,132.546443,2018-09-03 08:24:15,503.909,2.801754,N,NaN
4,421890,Radisson Blu Bristol,4245205c-b652-11e8-a724-005056a92e80,MTU Aero Engines RFP 2019,2019,LRA,INCLUDED,96.0,GBP,SIGNED_UP,...,2018-09-12,GBP,2018-09-12,0.89109,107.733226,2018-11-21 14:21:45,335.751,2.116504,N,NaN

In [6]:
df_2 = pd.read_excel('C:/Users/svi02/Documents/misc/bidrate_mp_hotels_list.xls',
                       sheet_name='Grid Results', 
                       encoding='utf-8')
df_2.head()

,HOTEL_ID,HOTEL_NAME,RFP_COUNT,AVG_SMART_BLIND_BID_RATE_EUR,AVG_SMART_BLIND_BID_RATE,BID_CURRENCY
0,10,relexa Bellevue,1,95.0,95.0,EUR
1,140,Avia,1,89.0,89.0,EUR
2,192,Deutsches Haus,4,89.0,89.0,EUR
3,302,Nordsee Hotel Bremerhaven,3,75.0,75.0,EUR
4,304,Europäischer Hof,4,120.0,120.0,EUR

In [9]:
res_df = pd.merge(left=df_1, 
                  right=df_2, 
                  on='HOTEL_ID',
                  # right_on = '',
                  # left_on = '',
                  how='right')
res_df.shape

(2666, 29)

In [10]:
res_df.to_excel('C:\\Users\\svi02\\Documents\\misc\\BidVSOffer_rates_hotels_new.xlsx', 
            sheet_name='TR_BBR', 
            header=True, 
            encoding='utf-8', 
            index=False, 
            freeze_panes=(1,1))

THE END