In [67]:
import boto3
import awswrangler as wr
s3 = boto3.client('s3')

In [6]:
bucket_name ='hrs-dna-hpo'
key_folder = 'hpo_result_excels'
dest_folder='Downloads/HPO/'
# file_name=input()
file_name='[HPO][BID_ANALYSIS][01d6d362] - Deutsche Post DHL Group Transient RFP 2021-2022.xlsm'

s3.download_file(bucket_name, key_folder+'/'+file_name, dest_folder+file_name)

In [9]:
hpo_results = wr.s3.read_excel(f's3://{bucket_name}/{key_folder}/{file_name}',sheet_name='HPO Results')

In [14]:
import pandas as pd
pd.set_option('display.max_columns', None)
hpo_results.head()

,RFP_PROCESS_ID,PFX_TIMESTAMP,RFP_ID,RFP_NAME,RFP_F_KEY,RFP_COMPANY_KEY,RFP_COMPANY_NAME,RFP_PHASE,RFP_RATE_TYPE,RFP_CURRENCY_DATE,RFP_ANALYSIS_CURRENCY,SOURCING_AGENT,RFP_RATE_VALIDITY_FROM,RFP_RATE_VALIDITY_TO,RFP_RATE_VALIDITY_DAYS,RFP_RATE_VALIDITY_YEAR,RFP_START_DATE,RFP_END_DATE,RFP_HOTEL_WORLD_REGION,RFP_HOTEL_COUNTRY_ID,RFP_HOTEL_COUNTRY_NAME,RFP_HOTEL_COUNTRY_CODE,RFP_DESTINATION_ID,RFP_DESTINATION_NAME,RFP_DESTINATION_MPD,RFP_POI_ID,RFP_POI_NAME,RFP_POI_LATITUDE,RFP_POI_LONGITUDE,RFP_POI_IS_VPOI,RFP_HOTEL_ID,RFP_HOTEL_NAME,RFP_HOTEL_CHAIN_ID,RFP_HOTEL_CHAIN_NAME,RFP_HOTEL_CHAIN_CLUSTER,RFP_HOTEL_CURRENCY,RFP_HOTEL_EXCHANGE_RATE_TO_ANALYSIS_CURRENCY,RFP_HOTEL_CITY_ID,RFP_HOTEL_CITY_NAME,RFP_HOTEL_LATITUDE,RFP_HOTEL_LONGITUDE,RFP_HOTEL_STATUS_ID,RFP_HOTEL_STATUS_NAME,RFP_HOTEL_CONTRACT_ID,RFP_HOTEL_CONTRACT_STATUS,RFP_HOTEL_CLEAN_LABEL,RFP_HOTEL_GREEN_CLASS_ID,RFP_HOTEL_GREEN_CLASS,RFP_HOTEL_IS_SMART_HOTEL,RFP_HOTEL_IS_VCC_HOTEL,RFP_HOTEL_RATING_GOOGLE,RFP_HOTEL_RATING_HRS,RFP_HOTEL_CATEGORY,RFP_HOTEL_ROOMS_CAPACITY,RFP_HOTEL_RATE_AUDIT_AVAILIBILITY,RFP_HOTEL_RATE_AUDIT_CORRECTNESS,RFP_HOTEL_IS_CCR_HOTEL,RFP_HOTEL_IS_MARKETPLACE,RFP_HOTEL_MARKETPLACE_CONTRACT_TYPE,RFP_HOTEL_IS_INCREMENTAL_BUSINESS,RFP_HOTEL_IS_INCREMENTAL_BUSINESS_CONTINUATION,RFP_HOTEL_IS_INCREMENTAL_BUSINESS_SUCCESS,RFP_HOTEL_IS_CONTRACTED_HOTEL,RFP_HOTEL_IS_BASELINE_HOTEL,RFP_HOTEL_FLAG,RFP_HOTEL_RFP_CHAIN_NAME,RFP_HOTEL_STATUS,RFP_HOTEL_DISTANCE_TO_POI,RFP_HOTEL_ROOMNIGHTS_ANALYSED,RFP_HOTEL_ROOMNIGHTS_ANALYSED_SHARE,RFP_HOTEL_ANALYZED_SPEND,RFP_HOTEL_OCCUPANCY,SOURCE_ALLOTMENTS,RN_CLUSTER,RATE_CLUSTER,CLIENT_HOTEL_AVG_CANCELLATION_RATE,CLIENT_HOTEL_AVG_CANCELLATION_PERIOD,RFP_HOTEL_BASELINE_RATE_SOURCE,RFP_HOTEL_BASELINE_RATE_TYPE,RFP_HOTEL_BASELINE_RATE,RFP_HOTEL_BASELINE_RATE_ROD,AVG_BOOKED_RATE,RFP_HOTEL_BASELINE_RATE_ADJUSTED,RFP_HOTEL_BASELINE_RATE_ORIGINAL_CURRENCY,RFP_HOTEL_BASELINE_RATE_ORIGINAL,RFP_HOTEL_BASELINE_RATE_IN_OFFER_TYPE,RFP_HOTEL_NORMALISED_RATE,RFP_HOTEL_BASELINE_NORMALISED_RATE,RFP_HOTEL_BASELINE_BREAKFAST_PRICE,RFP_HOTEL_BASELINE_CXL_POLICY,RFP_HOTEL_BASELINE_CXL_COSTS_PER_RN,RFP_HOTEL_BASELINE_CXL_COSTS_TOTAL,RFP_HOTEL_BASELINE_RATE_EST_GROSS,RFP_HOTEL_BASELINE_WEIGHT,RFP_HOTEL_ROOMNIGHTS_ANALYSED_ADJUSTED,RFP_HOTEL_BASELINE_SPEND_ADJUSTED,RFP_HOTEL_BENCHMARK_RATE,HOTEL_RATE_LOWER_BOUND_FINAL,HOTEL_RATE_UPPER_BOUND_FINAL,RATE_TYPE_SMART_BID,AMOUNT_SMART_BID,RFP_HOTEL_MIN_RFP_BID_TYPE,RFP_HOTEL_MIN_RFP_BID,RFP_HOTEL_PUBLIC_ADR,RFP_HOTEL_CCR_HOTEL_TYPE,RFP_HOTEL_CCR_FLOATING_PERC,RFP_HOTEL_CCR_BENCHMARK_TYPE,RFP_HOTEL_CCR_BENCHMARK,RFP_HOTEL_CCR_SCENARIO_ROOMNIGHTS_FORECASTED,RFP_HOTEL_CCR_SCENARIO_SPEND_FORECASTED,RFP_HOTEL_CCR_SCENARIO_SAVING_FORECASTED,RFP_TARGET_RATE_SOURCE,RFP_TARGET_RATE_TYPE,RFP_HOTEL_TARGET_RATE,RFP_HOTEL_TARGET_RATE_UPLOAD_CURRENCY,RFP_HOTEL_TARGET_RATE_IN_UPLOAD_CURRENCY,RFP_HOTEL_ROOMNIGHTS_FORECASTED,RFP_HOTEL_ROOMNIGHTS_FORECASTED_RN_CLUSTER,RFP_HOTEL_ROOMNIGHTS_FORECASTED_SHARE,RFP_HOTEL_SPEND_FORECASTED,RFP_HOTEL_OPTIMAL_PF_ROOMNIGHTS_FORECASTED_ADJUSTED,RFP_HOTEL_OPTIMAL_PF_SPEND_FORECASTED_ADJUSTED,TARGET_RATE_CLUSTER,RFP_HOTEL_LRA_SURCHARGE,BID_LRA_SURCHARGE_PERC,RATE_TYPE_BEST_DEAL,RFP_HOTEL_BID,AMOUNT_BEST_DEAL,RFP_HOTEL_BID_IS_OUTLIER,AMOUNT_OFFERED_BREAKFAST,BID_BREAKFAST_SURCHARGE_PERC,AMOUNT_BREAKFAST_HOTEL,GBTA_BID_TEXT,GBTA_BID_HOURS,CXL_BID_COSTS_PER_RN,CXL_BID_COSTS,CXL_NORMALISED_BID,RFP_HOTEL_BID_EST_GROSS,TOTAL_TAX_ADDED_ORIGINAL,REBID_TARGET_ACTION,AMOUNT_REBID_TARGET,RFP_HOTEL_RECO_SCORE,RFP_HOTEL_RECO_RANK,RFP_HOTEL_AH_RECO_RANK,RFP_HOTEL_USER_DECISION,RFP_HOTEL_IS_OPTIMAL_PORTFOLIO,RFP_HOTEL_OPTIMAL_PORTFOLIO_SOURCE,RFP_IS_SOLICIT_HOTEL,RFP_HOTEL_IS_OPTIMAL_PORTFOLIO_CONTRACTED,RFP_HOTEL_IS_OPTIMAL_PORTFOLIO_CCR,RFP_HOTEL_OPTIMAL_PF_OCCUPANCY_FORECASTED,FUTURE_PF_OCCUPANCY_FORECASTED,ERFP_BASELINE_BLACKOUT_DAYS,ERFP_BASELINE_TRADEFAIR_DAYS,ERFP_BASELINE_TAXES_INCLUDED,ERFP_BASELINE_LODGING_TAX,ERFP_BASELINE_STATE_TAX,ERFP_BASELINE_CITY_TAX,ERFP_BASELINE_VAT_TAX,ERFP_BASELINE_SERVICE_TAX,ERFP_BASELINE_OCCUPANCY_TAX,ERFP_BASELINE_OTHER_TAX,ERFP_BASELINE_AMENITIES_CURRENCY,ERFP_BASELINE_WIFI_INCLUDED,ERFP_BASELINE_WIFI_PRICE,ERFP_BASELINE_LAN_INCLUDED,ERFP_BASELINE_LAN_PRICE,ERFP_BASELINE_PARKING_INCLUDED,ERFP_BASELINE_PARKING_PRICE,ERFP_BASELINE_AIRPORT_TRANSFER_INCLUDED,ERFP_BASELINE_AIRPORT_TR_PRICE,ERFP_BASELINE_OFFICE_TRANSFER_INCLUDED,ERFP_BASELINE_OFFICE_TR_PRICE,ERFP_BASELINE_FITNESS_ROOM_INCLUDED,ERFP_BASELINE_FITNESS_PRICE,ERFP_BASELINE_BOTTLE_OF_WATER_INCLUDED,ERFP_BASELINE_WATER_PRICE,ERFP_BID_BLACKOUT_DAYS,ERFP_BID_CLOSING_PERIOD_DAYS,ERFP_BID_CITY_TAX_INCLUDED,ERFP_BID_IS_CITY_TAX_PERCENTAGE,ERFP_BID_CITY_TAX_AMOUNT,ERFP_BID_LODGING_TAX_INCLUDED,ERFP_BID_IS_LODGING_TAX_PERCENTAGE,ERFP_BID_LODGING_TAX_AMOUNT,ERFP_BID_STATE_TAX_INCLUDED,ERFP_BID_IS_STATE_TAX_PERCENTAGE,ERFP_BID_STATE_TAX_AMOUNT,ERFP_BID_OCCUPANCY_TAX_INCLUDED,ERFP_BID_IS_OCCUPANCY_TAX_PERCENTAGE,ERFP_BID_OCCUPANCY_TAX_AMOUNT,ERFP_BID_SERVICE_RESORT_FEE_INCLUDED,ERFP_BID_IS_SERVICE_RESORT_FEE_PERCENTAGE,ERFP_BID_SERVICE_RESORT_FEE_AMOUNT,ERFP_BID_LOGIS_TAX_INCLUDED,ERFP_BID_IS_LOGIS_TAX_PERCENTAGE,ERFP_BID_LOGIS_TAX_AMOUNT,ERFP_BID_GST_TAX_INCLUDED,ERFP_BID_IS_GST_TAX_PERCENTAGE,ERFP_BID_GST_TAX_AMOUNT,ERFP_BID_OTHER_TAX_INCLUDED,ERFP_BID_IS_OTHER_TAX_PERCENTAGE,ERFP_BID_OTHER_TAX_AMOUNT,ERFP_BID_WIFI_INCLUDED,ERFP_BID_WIFI_PRICE,ERFP_BID_LAN_INCLUDED,ERFP_BID_LAN_PRICE,ERFP_BID_PARKING_INCLUDED,ERFP_BID_PARKING_PRICE,ERFP_BID_FITNESS_ROOM_INCLUDED,ERFP_BID_FITNESS_PRICE,ERFP_BID_AIRPORT_TRANSFER_INCLUDE,ERFP_BID_AIRPORT_TR_PRICE,ERFP_BID_OFFICE_TRANSFER_INCLUDED,ERFP_BID_OFFICE_TR_PRICE,ERFP_BID_WATER_BOTTLE_INCLUDED,ERFP_BID_WATER_BOTTLE_PRICE,MASTER_USER_DECISION,MASTER_USER_ACCEPTED_RATE_TYPE,MASTER_USER_ACCEPTED_RATE,RFP_DISTRIBUTION_LOGIC
0,01d6d362-508d-44e2-a9d1-912c92ecea5f,2021-05-25 15:39:21.237000,f9ab56ae-436c-49a4-b747-88a267ebf63d,Deutsche Post DHL Group Transient RFP 2021-2022,140,1143,Deutsche Post DHL Group,BID_ANALYSIS,LRA_INCL,2021-03-18,EUR,llu05,2021-07-01,2022-06-30,364,2021,NaN,NaN,Europe,33,Germany,DE,7812fae5-16d3-4ca4-8c36-090d35ac442e,"Dusseldorf, Germany",NaN,3dcd7dae-5368-4fed-a6f7-6ea333428c0e,DP Düsseldorf 1,51.282521,6.772351,0,31212,Lindner Hotel Airport,229,Lindner Hotels & Resorts,Regional,EUR,1.0,97205,Düsseldorf (Nordrhein-Westfalen),51.273665,6.779932,0,open,1,free sale,Y - Self,1.0,A,0,1,8.2,8.53,4,241,0.7510,0.9842,Y,1,MPP1_0,N,N,N,N,Y,AH,NaN,proposalSubmitted,1.116,17,NaN,2298.003016,0.0004,NO,LOW,HIGH,0.00,72,AVG BOOKED RATE,NLRA_INCL,135.176648,Y,135.176648,135.176648,EUR,NaN,135.176648,114.685206,147.058341,NaN,NaN,0.0,NaN,NaN,1.0000,0,0.00000,91.088999,79.212083,198.030207,NaN,NaN,LRA_INCL,125.384700,118.21986,FIXED,0,LRA_EXCL,107.878608,NaN,NaN,NaN,UPLOADED_TARGET_RATE,LRA_INCL,100.30776,EUR,84.0,0,LOW,0.00000,0.0000,0,0.0000,HIGH,NaN,NaN,NLRA_INCL,113.443300,113.443300,N,11.94140,NaN,11.94140,18:00 am T,0,0.0,NaN,113.443300,113.443300,0.00,ACCEPT,113.443300,177.71,1,NaN,NaN,0,User,N,NaN,0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19.0,19.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,7.0,1.0,1.0,19.0,NaN,NaN,NaN,Y,0.0,N,0.0,N,22.0,Y,0.0,N,0.0,N,0.0,N,0.0,NaN,NaN,NaN,POI
1,01d6d362-508d-44e2-a9d1-912c92ecea5f,2021-05-25 15:39:21.237000,f9ab56ae-436c-49a4-b747-88a267ebf63d,Deutsche Post DHL Group Transient RFP 2021-2022,140,1143,Deutsche Post DHL Group,BID_ANALYSIS,LRA_INCL,2021-03-18,EUR,llu05,2021-07-01,2022-06-30,364,2021,NaN,NaN,Europe,15,Belgium,BE,5883c08d-1d9e-444d-92a9-a80896d7e0da,"Diegem, Belgium",NaN,5883c08d-1d9e-444d-92a9-a80896d7e1a,"vPOI_Diegem, Belgium_1",50.886734,4.448258,0,91800,pentahotel Brussels Airport,1291,Pentahotels Germany GmbH,Regional,EUR,1.0,148670,Brussel (Brussel Hoofdstedelijk Gewest),50.884692,4.444442,0,open,1,free sale,Y - Self,1.0,A,0,1,7.6,5.70,3,87,0.3542,1.0000,Y,1,MP3_0,N,N,N,Y,Y,CH,NaN,proposalSubmitted,0.351,186,NaN,26431.094760,0.0107,NO,LOW,HIGH,0.02,55,CONTRACTED RATE,LRA_INCL,142.102660,N,151.058710,142.102660,EUR,119.0,142.102660,155.345673,150.378050,21.49452,0.0,0.0,NaN,NaN,0.1256,188,26715.30008,142.102660,91.094970,227.739216,NaN,NaN,LRA_INCL,137.779873,155.23820,FIXED,0,NLRA_EXCL,116.798833,1500.0,175198.2501,152826.2501,UPLOADED_TARGET_RATE,LRA_INCL,128.96712,EUR,108.0,0,LOW,0.00000,0.0000,0,0.0000,HIGH,NaN,NaN,LRA_INCL,137.779873,137.779873,N,8.95605,NaN,8.95605,6:00PM,0,0.0,NaN,137.779873,144.347643,5.50,REDUCTION,127.892394,193.76,4,NaN,CCR,0,User,N,NaN,1,0.0,0.0,15.0,0.0,NO INFO,EXCLUDED,EXCLUDED,EXCLUDED,INCLUDED,EXCLUDED,EXCLUDED,EXCLUDED,EUR,Y,0.0,NaN,NaN,N,16.0,Y,0.0,NaN,NaN,Y,0.0,NaN,NaN,8.0,8.0,0.0,0.0,5.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,6.0,1.0,1.0,21.0,NaN,NaN,NaN,Y,0.0,N,0.0,N,16.0,Y,0.0,N,0.0,N,0.0,N,0.0,ACCEPTED,LRA_INCL,115.38,POI
2,01d6d362-508d-44e2-a9d1-912c92ecea5f,2021-05-25 15:39:21.237000,f9ab56ae-436c-49a4-b747-88a267ebf63d,Deutsche Post DHL Group Transient RFP 2021-2022,140,1143,Deutsche Post DHL Group,BID_ANALYSIS,LRA_INCL,2021-03-18,EUR,llu05,2021-07-01,2022-06-30,364,2021,NaN,NaN,Europe,33,Germany,DE,d0cfb889-cf12-4188-9f2d-ccf097644dc3,"Cologne, Germany",NaN,d0cfb889-cf12-4188-9f2d-ccf09764413,"vPOI_Cologne, Germany_1",50.937647,6.953211,0,413237,Azimut,1484,Azimut Hotels Company Europe,unknown,EUR,1.0,62901,Köln (Nordrhein-Westfalen),50.948962,6.951560,0,open,1,free sale,Y - Self,1.0,A,0,1,7.8,7.88,4,190,0.5978,0.9666,N,0,NaN,N,N,N,Y,Y,CH,NaN,proposalRevised,1.262,272,NaN,26634.098560,0.0072,NO,LOW,HIGH,0.00,60,CONTRACTED RATE,LRA_INCL,97.919480,N,92.904092,97.919480,EUR,82.0,97.919480,103.937946,99.830104,7.16484,0.0,0.0,NaN,NaN,0.4982,593,58066.25164,86.001963,58.355234,145.889278,LRA_INCL,100.869006,LRA_INCL,97.919480,102.69604,NaN,0,NaN,NaN,NaN,NaN,NaN,UPLOADED_TARGET_RATE,LRA_INCL,85.97808,EUR,72.0,0,LOW,0.00000,0.0000,0,0.0000,HIGH,NaN,0.0,LRA_INCL,103.937946,103.937946,N,7.16484,0.62,7.16484,6:00 pm,0,0.0,NaN,103.937946,103.937946,0.00,REDUCTION,97.919480,183.29,3,NaN,NaN,0,User,N,NaN,0,0.0,0.0,19.0,16.0,NO INFO,EXCLUDED,EXCLUDED,EXCLUDED,INCLUDED,EXCLUDED,EXCLUDED,EXCLUDED,EUR,Y,7.0,NaN,NaN,N,15.0,NaN,0.0,NaN,NaN,Y,5.0,NaN,NaN,30.0,30.0,1.0,1.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,7.0,1.0,1.0,19.0,NaN,NaN,NaN,Y,7.5,N,0.0,N,17.5,Y,5.6,N,4.5,N,0.0,N,0.0,NaN,NaN,NaN,POI
3,01d6d362-508d-44e2-a9d1-912c92ecea5f,2021-05-25 15:39:21.237000,f9ab56ae-436c-49a4-b747-88a267ebf63d,Deutsche Post DHL Group Transient RFP 2021-2022,140,1143,Deutsche Post DHL Group,BID_ANALYSIS,LRA_INCL,2021-03-18,EUR,llu05,2021-07-01,2022-06-30,364,2021,NaN,NaN,Europe,33,Germany,DE,d0cfb889-cf12-4188-9f2d-ccf097644dc3,"Cologne, Germany",NaN,d0cfb889-cf12-4188-9f2d-ccf09761c3,"CLUSTER_1_Cologne, Germany",50.873322,7.127124,0,1142,Leonardo Hotel Köln Bonn Airport,1434,Leonardo Hotels,Regional,EUR,1.0,62901,Köln (Nordrhein-Westfalen),50.880910,7.109930,0,open,1,free sale,Y - Expert,2.0,B,0,1,8.4,8.24,4,177,0.9250,1.0000,Y,1,MPP3_0,N,N,N,Y,Y,CH,NaN,proposalSubmitted,1.470,192,1.000000,19488.364800,0.0054,NO,MEDIUM,HIGH,0.00,48,CONTRACTED RATE,LRA_INCL,101.501900,N,112.607402,101.501900,EUR,85.0,101.501900,106.576995,101.501900,7.16484,0.0,0.0,NaN,NaN,1.0000,180,18270.34200,101.501900,63.418387,158.547162,NaN,NaN,LRA_INCL,101.501900,95.53120,FIXED,0,NLRA_INCL,95.531200,1413.0,134985.5856,119685.5856,UPLOADED_TARGET_RATE,LRA_INCL,88.36636,EUR,74.0,180,MEDIUM,0.13139,18270.3420,180,18270.3420,HIGH,NaN,NaN,LRA_INCL,101.501900,101.501900,N,7.16484,6.00,7.16484,18:00 Uhr,0,0.0,NaN,101.501900,106.576995,4.25,REDUCTION,91.351710,240.55,1,NaN,NaN,1,User,N,NaN,1,0.0,1.0,24.0,0.0,NO INFO,EXCLUDED,EXCLUDED,EXCLUDED,INCLUDED,EXCLUDED,EXCLUDED,EXCLUDED,EUR,Y,0.0,NaN,NaN,N,15.0,Y,0.0,NaN,NaN,Y,0.0,NaN,NaN,30.0,30.0,0.0,1.0,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,7.0,1.0,1.0,19.0,NaN,NaN,NaN,Y,0.0,N,0.0,N,15.0,Y,0.0,Y,0.0,N,0.0,N,0.0,ACCEPTED,LRA_INCL,85.00,POI
4,01d6d362-508d-44e2-a9d1-912c92ecea5f,2021-05-25 15:39:21.237000,f9ab56ae-436c-49a4-b747-88a267ebf63d,Deutsche Post DHL Group Transient RFP 2021-2022,140,1143,Deutsche Post DHL Group,BID_ANALYSIS,LRA_INCL,2021-03-18,EUR,llu05,2021-07-01,2022-06-30,364,2021,NaN,NaN,Europe,33,Germany,DE,ebe09ff5-0e3c-40b2-8eeb-fa98c768b16d,"Bonn, Germany",NaN,ebe09ff5-0e3c-40b2-8eeb-fa98c7636d,"CLUSTER_3_Bonn, Germany",50.734290,7.102291,0,169690,Living Hotel Kanzler,528,Derag Hotel and Living,unknown,EUR,1.0,92734,Bonn (Nordrhein-Westfalen),50.722780,7.113030,0,open,1,free sale,Y - Expert,2.0,B,0,1,8.4,7.71,4,150,0.9906,0.9375,Y,0,NaN,N,N,N,Y,Y,CH,NaN,proposalSubmitted,1.484,631,0.232071,67815.210600,0.0210,NO,LOW,HIGH,0.03,44,CONTRACTED RATE,LRA_INCL,107.472600,N,136.967858,107.472600,EUR,90.0,107.472600,102.994575,107.723369,8.35898,0.0,0.0,NaN,NaN,0.1167,407,43741.34820,107.472600,72.473551,181.184474,NaN,NaN,LRA_INCL,102.696040,132.54954,FIXED,0,LRA_EXCL,119.414000,2849.0,340210.4860,303580.4860,UPLOADED_TARGET_RATE,LRA_INCL,102.69604,EUR,86.0,810,LOW,0.08644,83183.7924,810,83183.7924,MEDIUM,NaN,NaN,LRA_INCL,102.696040,102.696040,N,8.35898,7.00,8.35898,18 Uhr,0,0.0,NaN,102.696040,102.696040,0.00,ACCEPT,102.696040,266.21,1,NaN,NaN,1,User,N,NaN,1,0.0,5.0,0.0,3.0,NO INFO,EXCLUDED,EXCLUDED,EXCLUDED,INCLUDED,EXCLUDED,EXCLUDED,EXCLUDED,EUR,Y,0.0,NaN,NaN,N,14.0,NaN,0.0,NaN,NaN,Y,0.0,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,7.0,1.0,1.0,19.0,NaN,NaN,NaN,Y,0.0,N,0.0,N,14.0,Y,0.0,N,0.0,N,0.0,N,0.0,ACCEPTED,LRA_INCL,86.00,POI

In [12]:
hpo_results.shape

(2824, 221)

In [34]:
dusseldorf = hpo_results[hpo_results['RFP_HOTEL_CITY_ID']==97205]
dusseldorf.reset_index(drop=True,inplace=True)
dusseldorf.head()

,RFP_PROCESS_ID,PFX_TIMESTAMP,RFP_ID,RFP_NAME,RFP_F_KEY,RFP_COMPANY_KEY,RFP_COMPANY_NAME,RFP_PHASE,RFP_RATE_TYPE,RFP_CURRENCY_DATE,RFP_ANALYSIS_CURRENCY,SOURCING_AGENT,RFP_RATE_VALIDITY_FROM,RFP_RATE_VALIDITY_TO,RFP_RATE_VALIDITY_DAYS,RFP_RATE_VALIDITY_YEAR,RFP_START_DATE,RFP_END_DATE,RFP_HOTEL_WORLD_REGION,RFP_HOTEL_COUNTRY_ID,RFP_HOTEL_COUNTRY_NAME,RFP_HOTEL_COUNTRY_CODE,RFP_DESTINATION_ID,RFP_DESTINATION_NAME,RFP_DESTINATION_MPD,RFP_POI_ID,RFP_POI_NAME,RFP_POI_LATITUDE,RFP_POI_LONGITUDE,RFP_POI_IS_VPOI,RFP_HOTEL_ID,RFP_HOTEL_NAME,RFP_HOTEL_CHAIN_ID,RFP_HOTEL_CHAIN_NAME,RFP_HOTEL_CHAIN_CLUSTER,RFP_HOTEL_CURRENCY,RFP_HOTEL_EXCHANGE_RATE_TO_ANALYSIS_CURRENCY,RFP_HOTEL_CITY_ID,RFP_HOTEL_CITY_NAME,RFP_HOTEL_LATITUDE,RFP_HOTEL_LONGITUDE,RFP_HOTEL_STATUS_ID,RFP_HOTEL_STATUS_NAME,RFP_HOTEL_CONTRACT_ID,RFP_HOTEL_CONTRACT_STATUS,RFP_HOTEL_CLEAN_LABEL,RFP_HOTEL_GREEN_CLASS_ID,RFP_HOTEL_GREEN_CLASS,RFP_HOTEL_IS_SMART_HOTEL,RFP_HOTEL_IS_VCC_HOTEL,RFP_HOTEL_RATING_GOOGLE,RFP_HOTEL_RATING_HRS,RFP_HOTEL_CATEGORY,RFP_HOTEL_ROOMS_CAPACITY,RFP_HOTEL_RATE_AUDIT_AVAILIBILITY,RFP_HOTEL_RATE_AUDIT_CORRECTNESS,RFP_HOTEL_IS_CCR_HOTEL,RFP_HOTEL_IS_MARKETPLACE,RFP_HOTEL_MARKETPLACE_CONTRACT_TYPE,RFP_HOTEL_IS_INCREMENTAL_BUSINESS,RFP_HOTEL_IS_INCREMENTAL_BUSINESS_CONTINUATION,RFP_HOTEL_IS_INCREMENTAL_BUSINESS_SUCCESS,RFP_HOTEL_IS_CONTRACTED_HOTEL,RFP_HOTEL_IS_BASELINE_HOTEL,RFP_HOTEL_FLAG,RFP_HOTEL_RFP_CHAIN_NAME,RFP_HOTEL_STATUS,RFP_HOTEL_DISTANCE_TO_POI,RFP_HOTEL_ROOMNIGHTS_ANALYSED,RFP_HOTEL_ROOMNIGHTS_ANALYSED_SHARE,RFP_HOTEL_ANALYZED_SPEND,RFP_HOTEL_OCCUPANCY,SOURCE_ALLOTMENTS,RN_CLUSTER,RATE_CLUSTER,CLIENT_HOTEL_AVG_CANCELLATION_RATE,CLIENT_HOTEL_AVG_CANCELLATION_PERIOD,RFP_HOTEL_BASELINE_RATE_SOURCE,RFP_HOTEL_BASELINE_RATE_TYPE,RFP_HOTEL_BASELINE_RATE,RFP_HOTEL_BASELINE_RATE_ROD,AVG_BOOKED_RATE,RFP_HOTEL_BASELINE_RATE_ADJUSTED,RFP_HOTEL_BASELINE_RATE_ORIGINAL_CURRENCY,RFP_HOTEL_BASELINE_RATE_ORIGINAL,RFP_HOTEL_BASELINE_RATE_IN_OFFER_TYPE,RFP_HOTEL_NORMALISED_RATE,RFP_HOTEL_BASELINE_NORMALISED_RATE,RFP_HOTEL_BASELINE_BREAKFAST_PRICE,RFP_HOTEL_BASELINE_CXL_POLICY,RFP_HOTEL_BASELINE_CXL_COSTS_PER_RN,RFP_HOTEL_BASELINE_CXL_COSTS_TOTAL,RFP_HOTEL_BASELINE_RATE_EST_GROSS,RFP_HOTEL_BASELINE_WEIGHT,RFP_HOTEL_ROOMNIGHTS_ANALYSED_ADJUSTED,RFP_HOTEL_BASELINE_SPEND_ADJUSTED,RFP_HOTEL_BENCHMARK_RATE,HOTEL_RATE_LOWER_BOUND_FINAL,HOTEL_RATE_UPPER_BOUND_FINAL,RATE_TYPE_SMART_BID,AMOUNT_SMART_BID,RFP_HOTEL_MIN_RFP_BID_TYPE,RFP_HOTEL_MIN_RFP_BID,RFP_HOTEL_PUBLIC_ADR,RFP_HOTEL_CCR_HOTEL_TYPE,RFP_HOTEL_CCR_FLOATING_PERC,RFP_HOTEL_CCR_BENCHMARK_TYPE,RFP_HOTEL_CCR_BENCHMARK,RFP_HOTEL_CCR_SCENARIO_ROOMNIGHTS_FORECASTED,RFP_HOTEL_CCR_SCENARIO_SPEND_FORECASTED,RFP_HOTEL_CCR_SCENARIO_SAVING_FORECASTED,RFP_TARGET_RATE_SOURCE,RFP_TARGET_RATE_TYPE,RFP_HOTEL_TARGET_RATE,RFP_HOTEL_TARGET_RATE_UPLOAD_CURRENCY,RFP_HOTEL_TARGET_RATE_IN_UPLOAD_CURRENCY,RFP_HOTEL_ROOMNIGHTS_FORECASTED,RFP_HOTEL_ROOMNIGHTS_FORECASTED_RN_CLUSTER,RFP_HOTEL_ROOMNIGHTS_FORECASTED_SHARE,RFP_HOTEL_SPEND_FORECASTED,RFP_HOTEL_OPTIMAL_PF_ROOMNIGHTS_FORECASTED_ADJUSTED,RFP_HOTEL_OPTIMAL_PF_SPEND_FORECASTED_ADJUSTED,TARGET_RATE_CLUSTER,RFP_HOTEL_LRA_SURCHARGE,BID_LRA_SURCHARGE_PERC,RATE_TYPE_BEST_DEAL,RFP_HOTEL_BID,AMOUNT_BEST_DEAL,RFP_HOTEL_BID_IS_OUTLIER,AMOUNT_OFFERED_BREAKFAST,BID_BREAKFAST_SURCHARGE_PERC,AMOUNT_BREAKFAST_HOTEL,GBTA_BID_TEXT,GBTA_BID_HOURS,CXL_BID_COSTS_PER_RN,CXL_BID_COSTS,CXL_NORMALISED_BID,RFP_HOTEL_BID_EST_GROSS,TOTAL_TAX_ADDED_ORIGINAL,REBID_TARGET_ACTION,AMOUNT_REBID_TARGET,RFP_HOTEL_RECO_SCORE,RFP_HOTEL_RECO_RANK,RFP_HOTEL_AH_RECO_RANK,RFP_HOTEL_USER_DECISION,RFP_HOTEL_IS_OPTIMAL_PORTFOLIO,RFP_HOTEL_OPTIMAL_PORTFOLIO_SOURCE,RFP_IS_SOLICIT_HOTEL,RFP_HOTEL_IS_OPTIMAL_PORTFOLIO_CONTRACTED,RFP_HOTEL_IS_OPTIMAL_PORTFOLIO_CCR,RFP_HOTEL_OPTIMAL_PF_OCCUPANCY_FORECASTED,FUTURE_PF_OCCUPANCY_FORECASTED,ERFP_BASELINE_BLACKOUT_DAYS,ERFP_BASELINE_TRADEFAIR_DAYS,ERFP_BASELINE_TAXES_INCLUDED,ERFP_BASELINE_LODGING_TAX,ERFP_BASELINE_STATE_TAX,ERFP_BASELINE_CITY_TAX,ERFP_BASELINE_VAT_TAX,ERFP_BASELINE_SERVICE_TAX,ERFP_BASELINE_OCCUPANCY_TAX,ERFP_BASELINE_OTHER_TAX,ERFP_BASELINE_AMENITIES_CURRENCY,ERFP_BASELINE_WIFI_INCLUDED,ERFP_BASELINE_WIFI_PRICE,ERFP_BASELINE_LAN_INCLUDED,ERFP_BASELINE_LAN_PRICE,ERFP_BASELINE_PARKING_INCLUDED,ERFP_BASELINE_PARKING_PRICE,ERFP_BASELINE_AIRPORT_TRANSFER_INCLUDED,ERFP_BASELINE_AIRPORT_TR_PRICE,ERFP_BASELINE_OFFICE_TRANSFER_INCLUDED,ERFP_BASELINE_OFFICE_TR_PRICE,ERFP_BASELINE_FITNESS_ROOM_INCLUDED,ERFP_BASELINE_FITNESS_PRICE,ERFP_BASELINE_BOTTLE_OF_WATER_INCLUDED,ERFP_BASELINE_WATER_PRICE,ERFP_BID_BLACKOUT_DAYS,ERFP_BID_CLOSING_PERIOD_DAYS,ERFP_BID_CITY_TAX_INCLUDED,ERFP_BID_IS_CITY_TAX_PERCENTAGE,ERFP_BID_CITY_TAX_AMOUNT,ERFP_BID_LODGING_TAX_INCLUDED,ERFP_BID_IS_LODGING_TAX_PERCENTAGE,ERFP_BID_LODGING_TAX_AMOUNT,ERFP_BID_STATE_TAX_INCLUDED,ERFP_BID_IS_STATE_TAX_PERCENTAGE,ERFP_BID_STATE_TAX_AMOUNT,ERFP_BID_OCCUPANCY_TAX_INCLUDED,ERFP_BID_IS_OCCUPANCY_TAX_PERCENTAGE,ERFP_BID_OCCUPANCY_TAX_AMOUNT,ERFP_BID_SERVICE_RESORT_FEE_INCLUDED,ERFP_BID_IS_SERVICE_RESORT_FEE_PERCENTAGE,ERFP_BID_SERVICE_RESORT_FEE_AMOUNT,ERFP_BID_LOGIS_TAX_INCLUDED,ERFP_BID_IS_LOGIS_TAX_PERCENTAGE,ERFP_BID_LOGIS_TAX_AMOUNT,ERFP_BID_GST_TAX_INCLUDED,ERFP_BID_IS_GST_TAX_PERCENTAGE,ERFP_BID_GST_TAX_AMOUNT,ERFP_BID_OTHER_TAX_INCLUDED,ERFP_BID_IS_OTHER_TAX_PERCENTAGE,ERFP_BID_OTHER_TAX_AMOUNT,ERFP_BID_WIFI_INCLUDED,ERFP_BID_WIFI_PRICE,ERFP_BID_LAN_INCLUDED,ERFP_BID_LAN_PRICE,ERFP_BID_PARKING_INCLUDED,ERFP_BID_PARKING_PRICE,ERFP_BID_FITNESS_ROOM_INCLUDED,ERFP_BID_FITNESS_PRICE,ERFP_BID_AIRPORT_TRANSFER_INCLUDE,ERFP_BID_AIRPORT_TR_PRICE,ERFP_BID_OFFICE_TRANSFER_INCLUDED,ERFP_BID_OFFICE_TR_PRICE,ERFP_BID_WATER_BOTTLE_INCLUDED,ERFP_BID_WATER_BOTTLE_PRICE,MASTER_USER_DECISION,MASTER_USER_ACCEPTED_RATE_TYPE,MASTER_USER_ACCEPTED_RATE,RFP_DISTRIBUTION_LOGIC
0,01d6d362-508d-44e2-a9d1-912c92ecea5f,2021-05-25 15:39:21.237000,f9ab56ae-436c-49a4-b747-88a267ebf63d,Deutsche Post DHL Group Transient RFP 2021-2022,140,1143,Deutsche Post DHL Group,BID_ANALYSIS,LRA_INCL,2021-03-18,EUR,llu05,2021-07-01,2022-06-30,364,2021,NaN,NaN,Europe,33,Germany,DE,7812fae5-16d3-4ca4-8c36-090d35ac442e,"Dusseldorf, Germany",NaN,3dcd7dae-5368-4fed-a6f7-6ea333428c0e,DP Düsseldorf 1,51.282521,6.772351,0,31212,Lindner Hotel Airport,229,Lindner Hotels & Resorts,Regional,EUR,1.0,97205,Düsseldorf (Nordrhein-Westfalen),51.273665,6.779932,0,open,1,free sale,Y - Self,1.0,A,0,1,8.2,8.53,4,241,0.7510,0.9842,Y,1,MPP1_0,N,N,N,N,Y,AH,NaN,proposalSubmitted,1.116,17,NaN,2298.003016,0.0004,NO,LOW,HIGH,0.00,72,AVG BOOKED RATE,NLRA_INCL,135.176648,Y,135.176648,135.176648,EUR,NaN,135.176648,114.685206,147.058341,NaN,NaN,0.0,NaN,NaN,1.0,0,0.0,91.088999,79.212083,198.030207,NaN,NaN,LRA_INCL,125.384700,118.21986,FIXED,0,LRA_EXCL,107.878608,NaN,NaN,NaN,UPLOADED_TARGET_RATE,LRA_INCL,100.30776,EUR,84.0,0,LOW,0.0,0.0,0,0.0,HIGH,NaN,NaN,NLRA_INCL,113.443300,113.443300,N,11.941400,NaN,11.941400,18:00 am T,0,0.0,NaN,113.443300,113.443300,0.0,ACCEPT,113.443300,177.71,1,NaN,NaN,0,User,N,NaN,0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19.0,19.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,7.0,1.0,1.0,19.0,NaN,NaN,NaN,Y,0.0,N,0.0,N,22.0,Y,0.0,N,0.0,N,0.0,N,0.0,NaN,NaN,NaN,POI
1,01d6d362-508d-44e2-a9d1-912c92ecea5f,2021-05-25 15:39:21.237000,f9ab56ae-436c-49a4-b747-88a267ebf63d,Deutsche Post DHL Group Transient RFP 2021-2022,140,1143,Deutsche Post DHL Group,BID_ANALYSIS,LRA_INCL,2021-03-18,EUR,llu05,2021-07-01,2022-06-30,364,2021,NaN,NaN,Europe,33,Germany,DE,7812fae5-16d3-4ca4-8c36-090d35ac442e,"Dusseldorf, Germany",NaN,7812fae5-16d3-4ca4-8c36-090d35ac41e,"vPOI_Dusseldorf, Germany_1",51.220575,6.799531,0,920598,McDreams Düsseldorf-City,-1,individual,Individual,EUR,1.0,97205,Düsseldorf (Nordrhein-Westfalen),51.206849,6.822051,0,open,1,free sale,Y - Self,NaN,NaN,0,0,8.0,7.54,0,102,NaN,NaN,N,1,MP3_0,N,N,N,N,N,AH,NaN,proposalSubmitted,2.186,3,NaN,0.000000,0.0001,NO,LOW,HIGH,0.00,72,AVG BOOKED RATE,NLRA_INCL,58.871102,Y,58.871102,58.871102,EUR,NaN,62.131104,59.097989,NaN,NaN,NaN,0.0,NaN,NaN,0.0,0,0.0,53.724359,29.841559,93.274275,NaN,NaN,LRA_INCL,59.097989,64.48356,NaN,0,NaN,NaN,NaN,NaN,NaN,UPLOADED_TARGET_RATE,LRA_INCL,57.31872,EUR,48.0,0,LOW,0.0,0.0,0,0.0,HIGH,NaN,0.0,LRA_EXCL,45.365379,45.365379,N,13.732610,11.5,13.732610,24 Stunden,24,0.0,NaN,45.365379,59.097989,0.0,ACCEPT,45.365379,69.18,8,NaN,NaN,0,User,N,NaN,0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,24.0,24.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,7.0,1.0,1.0,19.0,NaN,NaN,NaN,Y,0.0,N,0.0,Y,0.0,N,0.0,N,0.0,N,0.0,N,0.0,NaN,NaN,NaN,POI
2,01d6d362-508d-44e2-a9d1-912c92ecea5f,2021-05-25 15:39:21.237000,f9ab56ae-436c-49a4-b747-88a267ebf63d,Deutsche Post DHL Group Transient RFP 2021-2022,140,1143,Deutsche Post DHL Group,BID_ANALYSIS,LRA_INCL,2021-03-18,EUR,llu05,2021-07-01,2022-06-30,364,2021,NaN,NaN,Europe,33,Germany,DE,7812fae5-16d3-4ca4-8c36-090d35ac442e,"Dusseldorf, Germany",NaN,7812fae5-16d3-4ca4-8c36-090d35ac41e,"vPOI_Dusseldorf, Germany_1",51.220575,6.799531,0,145707,City Apart,0,NaN,NaN,EUR,1.0,97205,Düsseldorf (Nordrhein-Westfalen),51.224932,6.787835,1,blocked,1,free sale,N,NaN,NaN,0,1,7.2,8.15,0,21,NaN,NaN,N,0,NaN,N,N,N,N,N,AH,NaN,proposalSubmitted,0.946,0,NaN,0.000000,0.0000,NO,LOW,NaN,0.00,72,PUBLIC RATE,NaN,65.677700,Y,NaN,65.677700,EUR,NaN,NaN,57.796376,NaN,NaN,NaN,0.0,NaN,NaN,0.0,0,0.0,57.796376,31.091823,77.728961,NaN,NaN,LRA_EXCL,52.542160,65.67770,NaN,0,NaN,NaN,NaN,NaN,NaN,UPLOADED_TARGET_RATE,LRA_INCL,52.54216,EUR,44.0,0,LOW,0.0,0.0,0,0.0,HIGH,NaN,NaN,LRA_EXCL,52.542160,52.542160,N,5.254216,NaN,5.254216,24,24,0.0,NaN,52.542160,52.542160,0.0,ACCEPT,52.542160,94.64,7,NaN,NaN,0,User,N,NaN,0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,24.0,24.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,7.0,NaN,NaN,NaN,NaN,NaN,NaN,Y,0.0,N,0.0,N,0.0,N,0.0,N,0.0,N,0.0,N,0.0,ACCEPTED,LRA_EXCL,44.0,POI
3,01d6d362-508d-44e2-a9d1-912c92ecea5f,2021-05-25 15:39:21.237000,f9ab56ae-436c-49a4-b747-88a267ebf63d,Deutsche Post DHL Group Transient RFP 2021-2022,140,1143,Deutsche Post DHL Group,BID_ANALYSIS,LRA_INCL,2021-03-18,EUR,llu05,2021-07-01,2022-06-30,364,2021,NaN,NaN,Europe,33,Germany,DE,7812fae5-16d3-4ca4-8c36-090d35ac442e,"Dusseldorf, Germany",NaN,7812fae5-16d3-4ca4-8c36-090d35ac41e,"vPOI_Dusseldorf, Germany_1",51.220575,6.799531,0,37319,Sir & Lady Astor,-1,individual,Individual,EUR,1.0,97205,Düsseldorf (Nordrhein-Westfalen),51.224652,6.793322,0,open,1,free sale,N,NaN,NaN,0,1,9.4,9.33,0,37,0.9629,0.9766,N,1,MP3_0,N,N,N,N,N,AH,NaN,participationRejected,0.626,1,NaN,0.000000,0.0001,NO,LOW,HIGH,0.00,72,AVG BOOKED RATE,NLRA_INCL,133.146610,Y,133.146610,133.146610,EUR,NaN,NaN,106.397874,146.461271,NaN,NaN,0.0,NaN,NaN,0.0,0,0.0,81.416465,53.224014,133.060632,NaN,NaN,NaN,NaN,96.72534,NaN,0,NaN,NaN,NaN,NaN,NaN,UPLOADED_TARGET_RATE,LRA_INCL,83.58980,EUR,70.0,0,LOW,0.0,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.970700,NaN,0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,107.84,5,NaN,NaN,0,System,N,NaN,0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,N,NaN,N,NaN,N,NaN,N,NaN,N,NaN,N,NaN,NaN,NaN,NaN,POI
4,01d6d362-508d-44e2-a9d1-912c92ecea5f,2021-05-25 15:39:21.237000,f9ab56ae-436c-49a4-b747-88a267ebf63d,Deutsche Post DHL Group Transient RFP 2021-2022,140,1143,Deutsche Post DHL Group,BID_ANALYSIS,LRA_INCL,2021-03-18,EUR,llu05,2021-07-01,2022-06-30,364,2021,NaN,NaN,Europe,33,Germany,DE,7812fae5-16d3-4ca4-8c36-090d35ac442e,"Dusseldorf, Germany",NaN,a7b83a65-7244-4c95-b7bd-90ebed523322,DP Düsseldorf 2,51.257353,6.779903,0,6717,Doria,-1,individual,Individual,EUR,1.0,97205,Düsseldorf (Nordrhein-Westfalen),51.236982,6.779299,0,open,1,free sale,Y - Self,NaN,NaN,0,0,7.8,7.97,3,44,0.7750,0.8611,N,0,NaN,N,N,N,Y,Y,CH,NaN,participationRejected,2.262,1,NaN,80.007380,0.0001,NO,LOW,HIGH,0.33,72,CONTRACTED RATE,LRA_INCL,80.007380,N,80.007380,80.007380,EUR,67.0,NaN,88.652954,80.652216,10.74726,0.0,0.0,NaN,NaN,1.0,0,0.0,74.036680,47.765600,119.414000,NaN,NaN,LRA_INCL,80.007380,83.58980,NaN,0,NaN,NaN,NaN,NaN,NaN,UPLOADED_TARGET_RATE,LRA_INCL,74.03668,EUR,62.0,0,LOW,0.0,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.747260,NaN,0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,83.86,2,NaN,NaN,0,System,N,NaN,0,0.0,0.0,10.0,0.0,NO INFO,EXCLUDED,EXCLUDED,EXCLUDED,INCLUDED,EXCLUDED,EXCLUDED,EXCLUDED,EUR,Y,0.0,NaN,NaN,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,N,NaN,N,NaN,N,NaN,N,NaN,N,NaN,N,NaN,NaN,NaN,NaN,POI

In [50]:
hpo_results[['RFP_HOTEL_ID', 'RFP_HOTEL_COUNTRY_NAME']] \
.groupby('RFP_HOTEL_COUNTRY_NAME', sort=True,).count() \
.sort_values('RFP_HOTEL_ID', ascending=False) \
.head(10)
#             .sort_values(['job','count'],ascending=False) \

                        RFP_HOTEL_ID
RFP_HOTEL_COUNTRY_NAME
USA                              876
Germany                          435
Mexico                           147
France                            95
Brazil                            90
Czech Republic                    82
Sweden                            71
Austria                           62
Switzerland                       61
Canada                            57

In [52]:
from collections import Counter
string="geeksforgeeks"
freq = Counter(string)

In [53]:
for i in string:
    if(freq[i] == 1):
        print(i)
        break

f

In [54]:
freq

Counter({'g': 2, 'e': 4, 'k': 2, 's': 2, 'f': 1, 'o': 1, 'r': 1})

1
g 1
e 1
e 1
k 1
s 1
f 1
o 1
r 1
g 1
e 1
e 1
k 1
s

In [70]:
s3 = boto3.resource('s3')
bucket = s3.Bucket('hrs-prod-published-data-lake')
location ='procurement-solutions/rel'
keys=[]
for obj in bucket.objects.all():
    key = obj.key
    if location in key:
        keys.append(key)
print(keys)

['procurement-solutions/rel_crs_flags_to_rate_type/20210916_112155_00061_zz7wy_4353fe1b-1caf-4695-be6e-0efe068f723e', 'procurement-solutions/rel_crs_flags_to_rate_type/20210916_112155_00061_zz7wy_5edc7761-cef5-4e29-b680-87b899149f04', 'procurement-solutions/rel_crs_flags_to_rate_type/20210916_112155_00061_zz7wy_d01715ed-7306-408f-9713-fb03b6263436', 'procurement-solutions/rel_crs_flags_to_rate_type/20210916_112155_00061_zz7wy_f2389976-6ea2-4e52-8396-a619f8597503']

In [71]:
data =wr.s3.read_parquet('s3://hrs-prod-published-data-lake/procurement-solutions/rel_crs_flags_to_rate_type/20210916_112155_00061_zz7wy_4353fe1b-1caf-4695-be6e-0efe068f723e')

ClientError: An error occurred (403) when calling the HeadObject operation: Forbidden

In [82]:
import glob
path ="O:\\DE\\Cologne\\BI\\Teams\\0010_BI_HotelSolutions\\0900_RedmineAttmnt\\Hotel\\2020\\09"
text_files = glob.glob(path + "/**/*.xlsx", recursive = True)

for file in text_files:
    if '55036' in file:
        print(file)

In [2]:
import requests
import json
import pandas as pd

### Initialize the dataframe
final_df = pd.DataFrame()

### API link
url = "http://prod-administration-service.pec.hrs.cc:8080/hrs/aurora/floating-rates"
parsed = json.loads(requests.get(url).text)
df = pd.DataFrame(parsed)
df.head()

,id,museId,pegasusBrands,fKey,beginInterval,endInterval,allowedRpcs,minimumDiscount,maximumDiscount
0,1,ACCOR,,34,1546300800000,1577750400000,OLY,NaN,NaN
1,2,ACCOR,,49,1293840000000,1640908800000,ZEI 0VY,NaN,NaN
2,3,ACCOR,,75,1420070400000,1577750400000,DBZ O9W,NaN,NaN
3,4,ACCOR,,87,1483228800000,1640908800000,M4K,NaN,NaN
4,5,ACCOR,,95,1483228800000,1577750400000,UVG,NaN,NaN

In [3]:
df.shape

(670, 9)

In [7]:
df[df['pegasusBrands'] !='']

,id,museId,pegasusBrands,fKey,beginInterval,endInterval,allowedRpcs,minimumDiscount,maximumDiscount
123,125,AMADEUS,BW; WW; ;,49,1451606400000,1640908800000,ZEI,NaN,NaN
124,126,AMADEUS,CN; DT; ES; GI; HG; HL; HH; HX; QQ; WA;,87,1483228800000,1640908800000,MRV,NaN,NaN
125,127,AMADEUS,AL; EL; GX; LC; MD; MK; SH; SI; WH; WI; XR; TX...,95,1483228800000,1577750400000,UNL,NaN,NaN
126,128,AMADEUS,GI;,140,1483228800000,1640908800000,DHL,NaN,NaN
127,129,AMADEUS,BW;,155,1546300800000,1577750400000,TRU,NaN,NaN
...,...,...,...,...,...,...,...,...,...
530,805,AMADEUS,GI; HL; TI; DV; BW; XW; WW; FG;,4826,1622505600000,1654041600000,13C,NaN,NaN
531,806,AMADEUS,GI; HL; TI; DV;,30141,1622505600000,1654041600000,13C,NaN,NaN
539,814,AMADEUS,CN; DT; ES; GI; HG; HL; HH; HX; QQ; WA; BW; WW;,15548,1623888000000,1640908800000,VWK,NaN,NaN
662,940,AMADEUS,BW; CN; DT; ES; GI; HG; HL; HH; HX; QQ; WA; AZ...,14876,1626048000000,1640908800000,OR1,NaN,NaN
667,945,AMADEUS,CN; DT; ES; GI; HG; HL; HH; HX; QQ; WA;,16315,1629936000000,1672444800000,9A6,NaN,NaN

In [21]:
# df.query('pegasusBrands.notnull()', engine='python')
df.query('pegasusBrands.notnull()', engine='python')

,id,museId,pegasusBrands,fKey,beginInterval,endInterval,allowedRpcs,minimumDiscount,maximumDiscount
0,1,ACCOR,,34,1546300800000,1577750400000,OLY,NaN,NaN
1,2,ACCOR,,49,1293840000000,1640908800000,ZEI 0VY,NaN,NaN
2,3,ACCOR,,75,1420070400000,1577750400000,DBZ O9W,NaN,NaN
3,4,ACCOR,,87,1483228800000,1640908800000,M4K,NaN,NaN
4,5,ACCOR,,95,1483228800000,1577750400000,UVG,NaN,NaN
...,...,...,...,...,...,...,...,...,...
665,943,SOLMELIA,,140,1629244800000,1672444800000,ON5 ON6,NaN,NaN
666,944,DERBYSOFT,,28646,1629849600000,1661904000000,YLD,NaN,NaN
667,945,AMADEUS,CN; DT; ES; GI; HG; HL; HH; HX; QQ; WA;,16315,1629936000000,1672444800000,9A6,NaN,NaN
668,946,SOLMELIA,,16988,1630281600000,1672444800000,ON3 ON4,NaN,NaN
669,947,IHG,,31351,1631059200000,1664496000000,IGN1R,NaN,NaN