In [3]:
from fuzzywuzzy import fuzz
from fuzzywuzzy import process
import pandas as pd

matching_list_1 = pd.read_excel("C:\\Users\\svi02\\Documents\\misc\\2900_green_hotels_cert.xlsx" ,
                                sheet_name = 'clean',
                                header=0)
matching_list_1.head()

                                    CSR_CERTIFIED_BY  count_num
0                       Allergy and Astma Federation          2
1                                        Auf Anfrage          1
2                                 Austrian Eco Label          1
3                Austrian Eco Label in November,2012          1
4  Austrian Eco-Label,Austrian Energy- Efficiency Pr          1

In [4]:
matching_list_2 = matching_list_1
matching_list_2.head()

                                    CSR_CERTIFIED_BY  count_num
0                       Allergy and Astma Federation          2
1                                        Auf Anfrage          1
2                                 Austrian Eco Label          1
3                Austrian Eco Label in November,2012          1
4  Austrian Eco-Label,Austrian Energy- Efficiency Pr          1

In [5]:
list_string = matching_list_1['CSR_CERTIFIED_BY'].values.tolist()
len(list_string)

251

In [7]:
choices = matching_list_2['CSR_CERTIFIED_BY'].values.tolist()
len(choices)

251

In [14]:
import time
possibilities = []
start_time = time.time()

for string in list_string:
    #print(string)
    possibility = process.extract(string, choices, limit=3, scorer=fuzz.token_sort_ratio)
    possibilities.append(possibility)
end_time = time.time()
print(end_time - start_time)

0.7749300003051758

In [15]:
temp_df = pd.DataFrame(possibilities)
temp_df['Actual_string'] = list_string
temp_df.columns = ['Option-1', 'Option-2','Option-3', 'Actual_string']
temp_df.head()

,Option-1,Option-2,Option-3,Actual_string
0,"(Allergy and Astma Federation, 100)","(Y,GreenKey Think Global,LEED and Energy Star,...","(United against waste, 46)",Allergy and Astma Federation
1,"(Auf Anfrage, 100)","(Green Key and BREAM, 47)","(Green Engage, 43)",Auf Anfrage
2,"(Austrian Eco Label, 100)","(Austrian Eco Label in November,2012, 68)","(Eco label, 67)",Austrian Eco Label
3,"(Austrian Eco Label in November,2012, 100)","(Austrian Eco Label, 68)","(Austrian Eco-Label,Austrian Energy- Efficienc...","Austrian Eco Label in November,2012"
4,"(Austrian Eco-Label,Austrian Energy- Efficienc...","(Austrian Eco Label in November,2012, 58)","(Austrian Eco Label, 55)","Austrian Eco-Label,Austrian Energy- Efficiency Pr"

In [16]:
temp_df.to_excel('C:\\Users\\svi02\\Documents\\misc\\Env_cert_list.xlsx', 
                  sheet_name = 'Match',
                  header = True,
                  encoding='utf-8',
                  index=False)