# Loading script for Green stay hotels in DWHPFX schema

In [24]:
import requests
import json
import pandas as pd
import time
import configparser
import pyexasol

In [35]:
def get_token(urlLogin, env):
    """ This function authenticates and returns token and refreshToken """
    auth = {"client_id": "f6eeddfe-b600-4fc8-b283-e66f5fa0e0aa", "client_secret": "45f8160f-0bee-43af-a7ac-3d1013c84a78"}
    response = requests.post(urlLogin, json=auth)
    if response.status_code == 200:
        data = response.text
        parsed = json.loads(data)
        token = parsed['token']
        refreshToken = parsed['refreshToken']
    return token, refreshToken

def GreenStayExtract(urlAuth, env='det'):
    """ This function fetches the data from the api and stores in a df """

    token, refreshToken = get_token(urlAuth, env)
    startTime = time.time()
    urlGet = f"https://api.hotel-audit.hrs.com/v2/audits/report/green?token={token}&page=1&size=500"
    getResponse = requests.get(urlGet)
    rename_columns = {'hkey': 'HOTEL_ID', 'created_date': 'CREATED_DATE', 'updated_date': 'UPDATED_DATE',
                      'report_year': 'REPORTING_YEAR', 'kilogramCarbonPOC': 'CARBON_KGS', 'literWaterPOC': 'WATER_LTS',
                      'kilogramWastePOC': 'WASTE_KGS', 'carbonClass': 'CARBON_CLASS', 'waterClass': 'WATER_CLASS',
                      'wasteClass': 'WASTE_CLASS', 'greenClass': 'GREEN_CLASS', 'type': 'GREEN_INSPECTION_TYPE',
                      'status': 'GREEN_INSPECTION_STATUS'
                      }

    if getResponse.status_code == 200:
        data = getResponse.text
        parsed = json.loads(data)
        print(f"Status code: {getResponse.status_code}")
    else:
        print("Error in fetching the pages")
        
    try:
        temp = []
        for x in range(int(parsed['total_pages'])):
            urlIter = f"https://api.hotel-audit.hrs.com/v2/audits/report/green?token={token}&page={x+1}&size=500"
            getResponse = requests.get(urlIter)

            if getResponse.status_code == 200:
                data = getResponse.text
                parsed = json.loads(data)
                temp.append(parsed.get('results'))
            else:
                print("Request failed page: {} ".format(x))
        flatten = [item for sublist in temp for item in sublist]
        dfRaw = pd.DataFrame(flatten) 
        dfRaw['created_date'] = dfRaw['created_date'].astype(str).str[:-6]
        dfRaw['updated_date'] = dfRaw['updated_date'].astype(str).str[:-6]
        dfRaw['created_date'] = pd.to_datetime(dfRaw['created_date'], utc=False)
        dfRaw['updated_date'] = pd.to_datetime(dfRaw['updated_date'], utc=False)
        dfRaw = dfRaw[dfRaw.hkey.notnull()]
        dfRaw = dfRaw[['hkey', 'created_date', 'updated_date', 'report_year', 'kilogramCarbonPOC', 'literWaterPOC',
                       'kilogramWastePOC', 'carbonClass', 'waterClass', 'wasteClass', 'greenClass', 'type', 'status']]
        dfRaw.rename(columns=rename_columns, inplace=True)
        df = dfRaw.sort_values('UPDATED_DATE').groupby('HOTEL_ID').tail(1)
        df['CREATED_DATE'] = pd.to_datetime(dfRaw['CREATED_DATE'], format='%Y%m%d', errors='ignore').dt.date
        df['UPDATED_DATE'] = pd.to_datetime(dfRaw['UPDATED_DATE'], format='%Y%m%d', errors='ignore').dt.date
        df['GREEN_INSPECTION_TYPE'] = df['GREEN_INSPECTION_TYPE'].apply(lambda x: x.upper())
        df['LDTS'] = time.strftime('%Y-%m-%d')
        print(f'Number of records having HOTEL_IDs {dfRaw.HOTEL_ID.nunique()}.')
        print(f'Number of records with duplicate HOTEL_IDs: {dfRaw.duplicated(subset="HOTEL_ID", keep="first").sum()}.')
        endTime = time.time() - startTime
        print(f'Time in minutes: {round(endTime / 60, 2)}')
    except Exception as e:
        endTime = time.time() - startTime
        print('Failed in function GreenScore - ')
        print(f'Time in minutes: {round(endTime / 60, 2)}')
        raise e
    return df


def GreenStayLoad(df): 
    """ This function is to load the data into Exasol DB -> DWHPFX schema """
    try:
        #Location of the ini file
        config = configparser.ConfigParser()
        ## Config location CHANGE
        config.read('C:\\Users\\svi02\\.spyder-py3\\pfxDET.ini')
        dsn=config['pfxDET']['dsn']
        user=config['pfxDET']['user']
        pwd=config['pfxDET']['pwd']
        schema=config['pfxDET']['schema']
        # Exasol connection
        connect = pyexasol.connect(dsn=dsn, user=user, password=pwd, schema=schema)
        connect.execute("TRUNCATE TABLE DWHPFX.GREEN_STAY_HOTELS")
        connect.import_from_pandas(df, table = ('DWHPFX','GREEN_STAY_HOTELS'))
        stmt = connect.last_statement()
        print(f'Number of records inserted  {stmt.rowcount()}.')
    except Exception as e:
        print('Failed in function GreenStayLoad - ')
        raise e

### Function call

In [36]:
df=GreenStayExtract('https://api.hotel-audit.hrs.com/auth/login')
# GreenStayLoad(df)
df.head()

Status code: 200

     0
0   89
1  103
2  110
3  206
4  217

### Test results in excel

In [106]:
from datetime import date
df.to_excel('C:\\Users\\svi02\\Documents\\misc\\'+str(date.today())+'_test.xlsx', 
              sheet_name='Sheet1', 
              header=True,
              encoding='utf-8',
              index=False,
              freeze_panes=(1,0) )

In [14]:
import pandas as pd

data = [(-1, -1, 0), (-1, 1, 1), (1, -1, 1), (1, 1, 0)]

dftest = pd.DataFrame(data, columns=['feature1', 'feature2', 'label'])

C:\Anaconda\lib\site-packages\numpy\_distributor_init.py:32: UserWarning: loaded more than 1 DLL from .libs:
C:\Anaconda\lib\site-packages\numpy\.libs\libopenblas.QVLO2T66WEPI7JZ63PS3HMOHFEY472BC.gfortran-win_amd64.dll
C:\Anaconda\lib\site-packages\numpy\.libs\libopenblas.TXA6YQSD3GCQQC22GEQ54J2UDCXDXHWN.gfortran-win_amd64.dll
  stacklevel=1)

In [15]:
dftest.corr()

          feature1  feature2  label
feature1       1.0       0.0    0.0
feature2       0.0       1.0    0.0
label          0.0       0.0    1.0

In [11]:
lastname: str = 100

In [12]:
lastname

100

In [3]:
int = 'Lakshmi'

In [4]:
int

'Lakshmi'

In [5]:
lastname :int

In [6]:
lastname

'Lakshmi'

In [105]:
urlAuth='https://api.hotel-audit.hrs.com/auth/login'
token, refreshToken = get_token(urlAuth, env='det')
startTime = time.time()
urlGet = f"https://api.hotel-audit.hrs.com/v2/audits/report?token={token}&page=1&size=1"
getResponse = requests.get(urlGet)
rename_columns = {'hkey': 'HOTEL_ID', 'created_date': 'CREATED_DATE', 'updated_date': 'UPDATED_DATE',
                  'report_year': 'REPORTING_YEAR', 'kilogramCarbonPOC': 'CARBON_KGS', 'literWaterPOC': 'WATER_LTS',
                  'kilogramWastePOC': 'WASTE_KGS', 'carbonClass': 'CARBON_CLASS', 'waterClass': 'WATER_CLASS',
                  'wasteClass': 'WASTE_CLASS', 'greenClass': 'GREEN_CLASS', 'type': 'GREEN_INSPECTION_TYPE',
                  'status': 'GREEN_INSPECTION_STATUS'
                  }

if getResponse.status_code == 200:
    data = getResponse.text
    parsed = json.loads(data)
    print(parsed['total_pages'])
    print(f"Status code: {getResponse.status_code}")
else:
    print("Error in fetching the pages")
# try:
#     temp=[]
#     for x in range(int(parsed['total_pages'])):
#         urlIter = f"https://api.hotel-audit.hrs.com/v2/audits/report/green?token={token}&page={x+1}&size=500"
#         getResponse = requests.get(urlIter)

#         if getResponse.status_code == 200:
#             data = getResponse.text
#             parsed = json.loads(data)
#             temp.append(parsed.get('results').values())
#         else:
#             print("Request failed page: {} ".format(x))
#         flatten = [item for sublist in temp for item in sublist]
#         dfRaw = pd.DataFrame(flatten)
#         dfRaw['created_date'] = dfRaw['created_date'].astype(str).str[:-6]
#         dfRaw['updated_date'] = dfRaw['updated_date'].astype(str).str[:-6]
#         dfRaw['created_date'] = pd.to_datetime(dfRaw['created_date'], utc=False)
#         dfRaw['updated_date'] = pd.to_datetime(dfRaw['updated_date'], utc=False)
#         dfRaw = dfRaw[dfRaw.hkey.notnull()]
#         dfRaw = dfRaw[['hkey', 'created_date', 'updated_date', 'report_year', 'kilogramCarbonPOC', 'literWaterPOC',
#                        'kilogramWastePOC', 'carbonClass', 'waterClass', 'wasteClass', 'greenClass', 'type', 'status']]
#         dfRaw.rename(columns=rename_columns, inplace=True)
#         df = dfRaw.sort_values('UPDATED_DATE').groupby('HOTEL_ID').tail(1)
#         df['CREATED_DATE'] = pd.to_datetime(dfRaw['CREATED_DATE'], format='%Y%m%d', errors='ignore').dt.date
#         df['UPDATED_DATE'] = pd.to_datetime(dfRaw['UPDATED_DATE'], format='%Y%m%d', errors='ignore').dt.date
#         df['GREEN_INSPECTION_TYPE'] = df['GREEN_INSPECTION_TYPE'].apply(lambda x: x.upper())
#         df['LDTS'] = time.strftime('%Y-%m-%d')
#         print(f'Number of records having HOTEL_IDs {dfRaw.HOTEL_ID.nunique()}.')
#         print(f'Number of records with duplicate HOTEL_IDs: {dfRaw.duplicated(subset="HOTEL_ID", keep="first").sum()}.')
#         endTime = time.time() - startTime
#         print(f'Time in minutes: {round(endTime / 60, 2)}')
# except Exception as e:
#         endTime = time.time() - startTime
#         print('Failed in function GreenScore - ')
#         print(f'Time in minutes: {round(endTime / 60, 2)}')
#         raise e

67549
Status code: 200

In [106]:
parsed

{'results': [{'id': '00005b15-b99c-444d-97bf-d3cd02f8c8db',
   'hkey': 431251,
   'name': 'Homewood Suites by Hilton Lawrenceville',
   'created_date': '2020-07-31T16:16:24.000Z',
   'updated_date': '2020-07-31T16:16:24.000Z',
   'checked': '1,2,3,4,5,6,8,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46',
   'link': 'https://www.hilton.com/en/corporate/cleanstay/',
   'program_name': 'Hilton CleanStayTM',
   'version': 1,
   'terms': 2,
   'services': None,
   'audit_date': None,
   'auditor_key': None,
   'chain_id': 240,
   'chain_name': 'Hilton Hotels Corporation',
   'brand_id': 1537,
   'brand_name': 'Homewood Suites by Hilton',
   'city_id': 168172,
   'city': 'Lawrenceville (Georgia)',
   'country_id': 165,
   'country': 'USA',
   'performance_cluster': None,
   'status': True,
   'type': 'cleansafe_self_inspection',
   'missed': ''}],
 'page_number': 1,
 'page_size': 1,
 'total_pages': 67549}

In [55]:
urlAuth='https://api.hotel-audit.hrs.com/auth/login'
token, refreshToken = get_token(urlAuth, env='det')
startTime = time.time()
urlGet = f"https://api.hotel-audit.hrs.com/v2/audits/report/geosure?token={token}&page=1&size=500"
getResponse = requests.get(urlGet)
rename_columns = {'hkey': 'HOTEL_ID', 'created_date': 'CREATED_DATE', 'updated_date': 'UPDATED_DATE',
                  'report_year': 'REPORTING_YEAR', 'kilogramCarbonPOC': 'CARBON_KGS', 'literWaterPOC': 'WATER_LTS',
                  'kilogramWastePOC': 'WASTE_KGS', 'carbonClass': 'CARBON_CLASS', 'waterClass': 'WATER_CLASS',
                  'wasteClass': 'WASTE_CLASS', 'greenClass': 'GREEN_CLASS', 'type': 'GREEN_INSPECTION_TYPE',
                  'status': 'GREEN_INSPECTION_STATUS'
                  }

if getResponse.status_code == 200:
    data = getResponse.text
    parsed = json.loads(data)
#     print(parsed)
    print(f"Status code: {getResponse.status_code}")
else:
    print("Error in fetching the pages")
try:
    dfRaw = pd.DataFrame()
    temp1=[]
    for x in range(2):
        urlIter = f"https://api.hotel-audit.hrs.com/v2/audits/report/geosure?token={token}&page={x+1}&size=500"
        getResponse = requests.get(urlIter)

        if getResponse.status_code == 200:
            data = getResponse.text
            parsed = json.loads(data)
            temp1.append(parsed.get('results'))
        else:
            print("Request failed page: {} ".format(x))
except Exception as e:
        endTime = time.time() - startTime
        print('Failed in function GreenScore - ')
        print(f'Time in minutes: {round(endTime / 60, 2)}')
        raise e
temp1

Status code: 200

[[{'hkey': -1,
   'gs_id': 'Q930301291',
   'gs_distance': 0.10350994103402734,
   'date': '2021-09-02T10:00:07.000Z',
   'gs_province': '',
   'gs_region': 'Africa',
   'gs_district': 'Beach Road',
   'gs_city': 'Sekondi - Takoradi',
   'gs_country': 'Ghana',
   'gs_type': 'None',
   'gs_countrycode': 'GH',
   'gs_population': 0,
   'composite': 56,
   'nightime': 49,
   'physical': 55,
   'women': 51,
   'theft': 61,
   'freedom': 68,
   'health': 52,
   'lgbtq': 51,
   'type': 'geosure',
   'status': True},
  {'hkey': 1,
   'gs_id': 'Q930406986',
   'gs_distance': 0.0002792566589836676,
   'date': '2021-09-02T10:00:07.000Z',
   'gs_province': 'Berlin',
   'gs_region': 'European Union',
   'gs_district': 'Tiergarten Süd',
   'gs_city': 'Berlin',
   'gs_country': 'Germany',
   'gs_type': 'Capital',
   'gs_countrycode': 'DE',
   'gs_population': 0,
   'composite': 69,
   'nightime': 64,
   'physical': 70,
   'women': 68,
   'theft': 45,
   'freedom': 83,
   'health': 72,
   'lgbtq': 76,
   'type': 'geosure',
   'status': True},
  {'hkey': 2,
   'gs_id': 'Q930406996',
   'gs_distance': 0.00020796933450366843,
   'date': '2021-09-02T10:00:07.000Z',
   'gs_province': 'Berlin',
   'gs_region': 'European Union',
   'gs_district': 'Wilmersdorf',
   'gs_city': 'Berlin',
   'gs_country': 'Germany',
   'gs_type': 'Capital',
   'gs_countrycode': 'DE',
   'gs_population': 0,
   'composite': 75,
   'nightime': 71,
   'physical': 82,
   'women': 74,
   'theft': 52,
   'freedom': 84,
   'health': 81,
   'lgbtq': 76,
   'type': 'geosure',
   'status': True},
  {'hkey': 3,
   'gs_id': 'Q930406986',
   'gs_distance': 0.00026301350738513525,
   'date': '2021-09-02T10:00:07.000Z',
   'gs_province': 'Berlin',
   'gs_region': 'European Union',
   'gs_district': 'Tiergarten Süd',
   'gs_city': 'Berlin',
   'gs_country': 'Germany',
   'gs_type': 'Capital',
   'gs_countrycode': 'DE',
   'gs_population': 0,
   'composite': 69,
   'nightime': 64,
   'physical': 70,
   'women': 68,
   'theft': 45,
   'freedom': 83,
   'health': 72,
   'lgbtq': 76,
   'type': 'geosure',
   'status': True},
  {'hkey': 4,
   'gs_id': 'Q930406931',
   'gs_distance': 0.00020877987741519446,
   'date': '2021-09-02T10:00:07.000Z',
   'gs_province': 'Berlin',
   'gs_region': 'European Union',
   'gs_district': 'Halensee',
   'gs_city': 'Berlin',
   'gs_country': 'Germany',
   'gs_type': 'Capital',
   'gs_countrycode': 'DE',
   'gs_population': 0,
   'composite': 73,
   'nightime': 69,
   'physical': 79,
   'women': 67,
   'theft': 49,
   'freedom': 84,
   'health': 85,
   'lgbtq': 76,
   'type': 'geosure',
   'status': True},
  {'hkey': 5,
   'gs_id': 'Q930401016',
   'gs_distance': 0.0002502030829437063,
   'date': '2021-09-02T10:00:07.000Z',
   'gs_province': 'Berlin',
   'gs_region': 'European Union',
   'gs_district': 'Charlottenburg-Nord',
   'gs_city': 'Berlin',
   'gs_country': 'Germany',
   'gs_type': 'Capital',
   'gs_countrycode': 'DE',
   'gs_population': 0,
   'composite': 73,
   'nightime': 68,
   'physical': 81,
   'women': 73,
   'theft': 48,
   'freedom': 82,
   'health': 75,
   'lgbtq': 78,
   'type': 'geosure',
   'status': True},
  {'hkey': 6,
   'gs_id': 'Q930406979',
   'gs_distance': 9.064237670000752e-05,
   'date': '2021-09-02T10:00:07.000Z',
   'gs_province': 'Berlin',
   'gs_region': 'European Union',
   'gs_district': 'Siemensstadt',
   'gs_city': 'Berlin',
   'gs_country': 'Germany',
   'gs_type': 'Capital',
   'gs_countrycode': 'DE',
   'gs_population': 0,
   'composite': 71,
   'nightime': 66,
   'physical': 78,
   'women': 63,
   'theft': 49,
   'freedom': 83,
   'health': 78,
   'lgbtq': 76,
   'type': 'geosure',
   'status': True},
  {'hkey': 7,
   'gs_id': 'Q930406986',
   'gs_distance': 0.00016131169725547138,
   'date': '2021-09-02T10:00:07.000Z',
   'gs_province': 'Berlin',
   'gs_region': 'European Union',
   'gs_district': 'Tiergarten Süd',
   'gs_city': 'Berlin',
   'gs_country': 'Germany',
   'gs_type': 'Capital',
   'gs_countrycode': 'DE',
   'gs_population': 0,
   'composite': 69,
   'nightime': 64,
   'physical': 70,
   'women': 68,
   'theft': 45,
   'freedom': 83,
   'health': 72,
   'lgbtq': 76,
   'type': 'geosure',
   'status': True},
  {'hkey': 8,
   'gs_id': 'Q930406159',
   'gs_distance': 0.000988797777656667,
   'date': '2021-09-02T10:00:07.000Z',
   'gs_province': 'Bremen',
   'gs_region': 'European Union',
   'gs_district': 'Sodenmatt',
   'gs_city': 'Bremen',
   'gs_country': 'Germany',
   'gs_type': 'None',
   'gs_countrycode': 'DE',
   'gs_population': 0,
   'composite': 75,
   'nightime': 71,
   'physical': 80,
   'women': 72,
   'theft': 63,
   'freedom': 85,
   'health': 74,
   'lgbtq': 77,
   'type': 'geosure',
   'status': True},
  {'hkey': 9,
   'gs_id': 'Q930401328',
   'gs_distance': 0.0005390810824128248,
   'date': '2021-09-02T10:00:07.000Z',
   'gs_province': 'Schleswig-Holstein',
   'gs_region': 'European Union',
   'gs_district': 'Overall',
   'gs_city': 'Kiel',
   'gs_country': 'Germany',
   'gs_type': 'Port City',
   'gs_countrycode': 'DE',
   'gs_population': 247548,
   'composite': 77,
   'nightime': 74,
   'physical': 74,
   'women': 75,
   'theft': 65,
   'freedom': 86,
   'health': 85,
   'lgbtq': 79,
   'type': 'geosure',
   'status': True},
  {'hkey': 10,
   'gs_id': 'Q930401275',
   'gs_distance': 0.00011431131309540533,
   'date': '2021-09-02T10:00:07.000Z',
   'gs_province': 'Hamburg',
   'gs_region': 'European Union',
   'gs_district': 'St. Georg',
   'gs_city': 'Hamburg',
   'gs_country': 'Germany',
   'gs_type': 'Port City',
   'gs_countrycode': 'DE',
   'gs_population': 0,
   'composite': 76,
   'nightime': 71,
   'physical': 75,
   'women': 70,
   'theft': 52,
   'freedom': 90,
   'health': 74,
   'lgbtq': 92,
   'type': 'geosure',
   'status': True},
  {'hkey': 11,
   'gs_id': 'Q930406140',
   'gs_distance': 0.00012188724830362943,
   'date': '2021-09-02T10:00:07.000Z',
   'gs_province': 'Bremen',
   'gs_region': 'European Union',
   'gs_district': 'Neu-Schwachhausen',
   'gs_city': 'Bremen',
   'gs_country': 'Germany',
   'gs_type': 'None',
   'gs_countrycode': 'DE',
   'gs_population': 0,
   'composite': 74,
   'nightime': 69,
   'physical': 72,
   'women': 74,
   'theft': 62,
   'freedom': 86,
   'health': 72,
   'lgbtq': 77,
   'type': 'geosure',
   'status': True},
  {'hkey': 12,
   'gs_id': 'Q930401272',
   'gs_distance': 0.00012641703362084963,
   'date': '2021-09-02T10:00:07.000Z',
   'gs_province': 'Hamburg',
   'gs_region': 'European Union',
   'gs_district': 'Schnelsen',
   'gs_city': 'Hamburg',
   'gs_country': 'Germany',
   'gs_type': 'Port City',
   'gs_countrycode': 'DE',
   'gs_population': 0,
   'composite': 77,
   'nightime': 73,
   'physical': 81,
   'women': 73,
   'theft': 65,
   'freedom': 87,
   'health': 79,
   'lgbtq': 76,
   'type': 'geosure',
   'status': True},
  {'hkey': 13,
   'gs_id': 'Q930406134',
   'gs_distance': 0.00019384159564877907,
   'date': '2021-09-02T10:00:07.000Z',
   'gs_province': 'Bremen',
   'gs_region': 'European Union',
   'gs_district': 'Mahndorf',
   'gs_city': 'Bremen',
   'gs_country': 'Germany',
   'gs_type': 'None',
   'gs_countrycode': 'DE',
   'gs_population': 0,
   'composite': 75,
   'nightime': 71,
   'physical': 80,
   'women': 71,
   'theft': 63,
   'freedom': 86,
   'health': 72,
   'lgbtq': 76,
   'type': 'geosure',
   'status': True},
  {'hkey': 14,
   'gs_id': 'Q930401273',
   'gs_distance': 0.0029518631046675787,
   'date': '2021-09-02T10:00:07.000Z',
   'gs_province': 'Hamburg',
   'gs_region': 'European Union',
   'gs_district': 'Sinstorf',
   'gs_city': 'Hamburg',
   'gs_country': 'Germany',
   'gs_type': 'Port City',
   'gs_countrycode': 'DE',
   'gs_population': 0,
   'composite': 76,
   'nightime': 72,
   'physical': 82,
   'women': 73,
   'theft': 65,
   'freedom': 87,
   'health': 74,
   'lgbtq': 77,
   'type': 'geosure',
   'status': True},
  {'hkey': 15,
   'gs_id': 'Q930401263',
   'gs_distance': 0.00014618591189090915,
   'date': '2021-09-02T10:00:07.000Z',
   'gs_province': 'Hamburg',
   'gs_region': 'European Union',
   'gs_district': 'Ottensen',
   'gs_city': 'Hamburg',
   'gs_country': 'Germany',
   'gs_type': 'Port City',
   'gs_countrycode': 'DE',
   'gs_population': 0,
   'composite': 75,
   'nightime': 70,
   'physical': 76,
   'women': 72,
   'theft': 59,
   'freedom': 88,
   'health': 75,
   'lgbtq': 78,
   'type': 'geosure',
   'status': True},
  {'hkey': 16,
   'gs_id': 'Q930401275',
   'gs_distance': 4.6139543367933574e-05,
   'date': '2021-09-02T10:00:07.000Z',
   'gs_province': 'Hamburg',
   'gs_region': 'European Union',
   'gs_district': 'St. Georg',
   'gs_city': 'Hamburg',
   'gs_country': 'Germany',
   'gs_type': 'Port City',
   'gs_countrycode': 'DE',
   'gs_population': 0,
   'composite': 76,
   'nightime': 71,
   'physical': 75,
   'women': 70,
   'theft': 52,
   'freedom': 90,
   'health': 74,
   'lgbtq': 92,
   'type': 'geosure',
   'status': True},
  {'hkey': 17,
   'gs_id': 'Q930406094',
   'gs_distance': 6.045845678328649e-05,
   'date': '2021-09-02T10:00:07.000Z',
   'gs_province': 'Bremen',
   'gs_region': 'European Union',
   'gs_district': 'Bahnhofsvorstadt',
   'gs_city': 'Bremen',
   'gs_country': 'Germany',
   'gs_type': 'None',
   'gs_countrycode': 'DE',
   'gs_population': 0,
   'composite': 74,
   'nightime': 69,
   'physical': 72,
   'women': 75,
   'theft': 57,
   'freedom': 86,
   'health': 77,
   'lgbtq': 77,
   'type': 'geosure',
   'status': True},
  {'hkey': 18,
   'gs_id': 'Q930406977',
   'gs_distance': 0.00024094042832897063,
   'date': '2021-09-02T10:00:07.000Z',
   'gs_province': 'Berlin',
   'gs_region': 'European Union',
   'gs_district': 'Schöneberg-Süd',
   'gs_city': 'Berlin',
   'gs_country': 'Germany',
   'gs_type': 'Capital',
   'gs_countrycode': 'DE',
   'gs_population': 0,
   'composite': 70,
   'nightime': 65,
   'physical': 72,
   'women': 61,
   'theft': 45,
   'freedom': 84,
   'health': 77,
   'lgbtq': 79,
   'type': 'geosure',
   'status': True},
  {'hkey': 19,
   'gs_id': 'Q930406641',
   'gs_distance': 8.525900006217756e-05,
   'date': '2021-09-02T10:00:07.000Z',
   'gs_province': 'Lower Saxony',
   'gs_region': 'European Union',
   'gs_district': 'Mitte',
   'gs_city': 'Hannover',
   'gs_country': 'Germany',
   'gs_type': 'None',
   'gs_countrycode': 'DE',
   'gs_population': 0,
   'composite': 73,
   'nightime': 68,
   'physical': 74,
   'women': 67,
   'theft': 50,
   'freedom': 87,
   'health': 82,
   'lgbtq': 77,
   'type': 'geosure',
   'status': True},
  {'hkey': 20,
   'gs_id': 'Q930401320',
   'gs_distance': 0.00013835900298827663,
   'date': '2021-09-02T10:00:07.000Z',
   'gs_province': 'Lower Saxony',
   'gs_region': 'European Union',
   'gs_district': 'Overall',
   'gs_city': 'Hannover',
   'gs_country': 'Germany',
   'gs_type': 'None',
   'gs_countrycode': 'DE',
   'gs_population': 538068,
   'composite': 76,
   'nightime': 71,
   'physical': 73,
   'women': 75,
   'theft': 64,
   'freedom': 85,
   'health': 76,
   'lgbtq': 81,
   'type': 'geosure',
   'status': True},
  {'hkey': 21,
   'gs_id': 'Q930401186',
   'gs_distance': 0.0015758273052218245,
   'date': '2021-09-02T10:00:07.000Z',
   'gs_province': 'Lower Saxony',
   'gs_region': 'European Union',
   'gs_district': 'Overall',
   'gs_city': 'Gottingen',
   'gs_country': 'Germany',
   'gs_type': 'None',
   'gs_countrycode': 'DE',
   'gs_population': 119801,
   'composite': 78,
   'nightime': 74,
   'physical': 75,
   'women': 77,
   'theft': 65,
   'freedom': 85,
   'health': 90,
   'lgbtq': 77,
   'type': 'geosure',
   'status': True},
  {'hkey': 22,
   'gs_id': 'Q930404034',
   'gs_distance': 0.0054548014718278715,
   'date': '2021-09-02T10:00:07.000Z',
   'gs_province': 'Bern',
   'gs_region': 'Western Europe',
   'gs_district': 'Murifeld',
   'gs_city': 'Bern',
   'gs_country': 'Switzerland',
   'gs_type': 'Capital',
   'gs_countrycode': 'CH',
   'gs_population': 0,
   'composite': 79,
   'nightime': 75,
   'physical': 86,
   'women': 77,
   'theft': 70,
   'freedom': 87,
   'health': 76,
   'lgbtq': 77,
   'type': 'geosure',
   'status': True},
  {'hkey': 23,
   'gs_id': 'Q930401327',
   'gs_distance': 0.007574097922376886,
   'date': '2021-09-02T10:00:07.000Z',
   'gs_province': 'Hessen',
   'gs_region': 'European Union',
   'gs_district': 'Overall',
   'gs_city': 'Kassel',
   'gs_country': 'Germany',
   'gs_type': 'None',
   'gs_countrycode': 'DE',
   'gs_population': 201585,
   'composite': 76,
   'nightime': 71,
   'physical': 79,
   'women': 64,
   'theft': 65,
   'freedom': 83,
   'health': 83,
   'lgbtq': 79,
   'type': 'geosure',
   'status': True},
  {'hkey': 24,
   'gs_id': 'Q930406656',
   'gs_distance': 0.005241573508711987,
   'date': '2021-09-02T10:00:07.000Z',
   'gs_province': 'Lower Saxony',
   'gs_region': 'European Union',
   'gs_district': 'Wettbergen',
   'gs_city': 'Hannover',
   'gs_country': 'Germany',
   'gs_type': 'None',
   'gs_countrycode': 'DE',
   'gs_population': 0,
   'composite': 75,
   'nightime': 71,
   'physical': 76,
   'women': 71,
   'theft': 65,
   'freedom': 86,
   'health': 75,
   'lgbtq': 76,
   'type': 'geosure',
   'status': True},
  {'hkey': 25,
   'gs_id': 'Q930401327',
   'gs_distance': 0.00016824565017408303,
   'date': '2021-09-02T10:00:07.000Z',
   'gs_province': 'Hessen',
   'gs_region': 'European Union',
   'gs_district': 'Overall',
   'gs_city': 'Kassel',
   'gs_country': 'Germany',
   'gs_type': 'None',
   'gs_countrycode': 'DE',
   'gs_population': 201585,
   'composite': 76,
   'nightime': 71,
   'physical': 79,
   'women': 64,
   'theft': 65,
   'freedom': 83,
   'health': 83,
   'lgbtq': 79,
   'type': 'geosure',
   'status': True},
  {'hkey': 26,
   'gs_id': 'Q930401186',
   'gs_distance': 0.007049388172978114,
   'date': '2021-09-02T10:00:07.000Z',
   'gs_province': 'Lower Saxony',
   'gs_region': 'European Union',
   'gs_district': 'Overall',
   'gs_city': 'Gottingen',
   'gs_country': 'Germany',
   'gs_type': 'None',
   'gs_countrycode': 'DE',
   'gs_population': 119801,
   'composite': 78,
   'nightime': 74,
   'physical': 75,
   'women': 77,
   'theft': 65,
   'freedom': 85,
   'health': 90,
   'lgbtq': 77,
   'type': 'geosure',
   'status': True},
  {'hkey': 27,
   'gs_id': 'Q930401320',
   'gs_distance': 9.604462552118947e-05,
   'date': '2021-09-02T10:00:07.000Z',
   'gs_province': 'Lower Saxony',
   'gs_region': 'European Union',
   'gs_district': 'Overall',
   'gs_city': 'Hannover',
   'gs_country': 'Germany',
   'gs_type': 'None',
   'gs_countrycode': 'DE',
   'gs_population': 538068,
   'composite': 76,
   'nightime': 71,
   'physical': 73,
   'women': 75,
   'theft': 64,
   'freedom': 85,
   'health': 76,
   'lgbtq': 81,
   'type': 'geosure',
   'status': True},
  {'hkey': 29,
   'gs_id': 'Q930107136',
   'gs_distance': 0.0022215407335519645,
   'date': '2021-08-25T16:31:26.000Z',
   'gs_province': '',
   'gs_region': 'Central America',
   'gs_district': 'Overall',
   'gs_city': 'St.Croix',
   'gs_country': 'United States Virgin Islands',
   'gs_type': 'Port City',
   'gs_countrycode': 'VI',
   'gs_population': 50601,
   'composite': 63,
   'nightime': 57,
   'physical': 64,
   'women': 70,
   'theft': 66,
   'freedom': 68,
   'health': 58,
   'lgbtq': 50,
   'type': 'geosure',
   'status': True},
  {'hkey': 30,
   'gs_id': 'Q930401328',
   'gs_distance': 6.34587118716729e-05,
   'date': '2021-09-02T10:00:07.000Z',
   'gs_province': 'Schleswig-Holstein',
   'gs_region': 'European Union',
   'gs_district': 'Overall',
   'gs_city': 'Kiel',
   'gs_country': 'Germany',
   'gs_type': 'Port City',
   'gs_countrycode': 'DE',
   'gs_population': 247548,
   'composite': 77,
   'nightime': 74,
   'physical': 74,
   'women': 75,
   'theft': 65,
   'freedom': 86,
   'health': 85,
   'lgbtq': 79,
   'type': 'geosure',
   'status': True},
  {'hkey': 31,
   'gs_id': 'Q930406074',
   'gs_distance': 8.021524936420053e-05,
   'date': '2021-09-02T10:00:07.000Z',
   'gs_province': 'North Rhine-Westphalia',
   'gs_region': 'European Union',
   'gs_district': 'Rüttenscheid',
   'gs_city': 'Essen',
   'gs_country': 'Germany',
   'gs_type': 'None',
   'gs_countrycode': 'DE',
   'gs_population': 0,
   'composite': 77,
   'nightime': 73,
   'physical': 77,
   'women': 76,
   'theft': 67,
   'freedom': 86,
   'health': 78,
   'lgbtq': 78,
   'type': 'geosure',
   'status': True},
  {'hkey': 32,
   'gs_id': 'Q930407014',
   'gs_distance': 0.0001120524358572011,
   'date': '2021-09-02T10:00:07.000Z',
   'gs_province': 'North Rhine-Westphalia',
   'gs_region': 'European Union',
   'gs_district': 'Sieker',
   'gs_city': 'Bielefeld',
   'gs_country': 'Germany',
   'gs_type': 'None',
   'gs_countrycode': 'DE',
   'gs_population': 0,
   'composite': 75,
   'nightime': 71,
   'physical': 79,
   'women': 74,
   'theft': 64,
   'freedom': 87,
   'health': 70,
   'lgbtq': 76,
   'type': 'geosure',
   'status': True},
  {'hkey': 33,
   'gs_id': 'Q930406070',
   'gs_distance': 0.00022743616277903154,
   'date': '2021-09-02T10:00:07.000Z',
   'gs_province': 'North Rhine-Westphalia',
   'gs_region': 'European Union',
   'gs_district': 'Margarethenhöhe',
   'gs_city': 'Essen',
   'gs_country': 'Germany',
   'gs_type': 'None',
   'gs_countrycode': 'DE',
   'gs_population': 0,
   'composite': 76,
   'nightime': 72,
   'physical': 76,
   'women': 75,
   'theft': 65,
   'freedom': 86,
   'health': 74,
   'lgbtq': 78,
   'type': 'geosure',
   'status': True},
  {'hkey': 34,
   'gs_id': 'Q930401182',
   'gs_distance': 0.004804462890623909,
   'date': '2021-09-02T10:00:07.000Z',
   'gs_province': 'North Rhine-Westphalia',
   'gs_region': 'European Union',
   'gs_district': 'Milse',
   'gs_city': 'Bielefeld',
   'gs_country': 'Germany',
   'gs_type': 'None',
   'gs_countrycode': 'DE',
   'gs_population': 0,
   'composite': 76,
   'nightime': 72,
   'physical': 81,
   'women': 73,
   'theft': 65,
   'freedom': 85,
   'health': 75,
   'lgbtq': 76,
   'type': 'geosure',
   'status': True},
  {'hkey': 35,
   'gs_id': 'Q930401041',
   'gs_distance': 8.339916266670045e-05,
   'date': '2021-09-02T10:00:07.000Z',
   'gs_province': 'North Rhine-Westphalia',
   'gs_region': 'European Union',
   'gs_district': 'Overall',
   'gs_city': 'Dortmund',
   'gs_country': 'Germany',
   'gs_type': 'None',
   'gs_countrycode': 'DE',
   'gs_population': 587010,
   'composite': 74,
   'nightime': 70,
   'physical': 68,
   'women': 68,
   'theft': 65,
   'freedom': 85,
   'health': 81,
   'lgbtq': 76,
   'type': 'geosure',
   'status': True},
  {'hkey': 36,
   'gs_id': 'Q930400149',
   'gs_distance': 0.00035045369110903196,
   'date': '2021-09-02T10:00:07.000Z',
   'gs_province': 'Liege',
   'gs_region': 'European Union',
   'gs_district': 'Overall',
   'gs_city': 'Liege',
   'gs_country': 'Belgium',
   'gs_type': 'None',
   'gs_countrycode': 'BE',
   'gs_population': 197327,
   'composite': 75,
   'nightime': 71,
   'physical': 71,
   'women': 79,
   'theft': 61,
   'freedom': 90,
   'health': 73,
   'lgbtq': 77,
   'type': 'geosure',
   'status': True},
  {'hkey': 37,
   'gs_id': 'Q930401182',
   'gs_distance': 0.005124859928301143,
   'date': '2021-09-02T10:00:07.000Z',
   'gs_province': 'North Rhine-Westphalia',
   'gs_region': 'European Union',
   'gs_district': 'Milse',
   'gs_city': 'Bielefeld',
   'gs_country': 'Germany',
   'gs_type': 'None',
   'gs_countrycode': 'DE',
   'gs_population': 0,
   'composite': 76,
   'nightime': 72,
   'physical': 81,
   'women': 73,
   'theft': 65,
   'freedom': 85,
   'health': 75,
   'lgbtq': 76,
   'type': 'geosure',
   'status': True},
  {'hkey': 38,
   'gs_id': 'Q930401406',
   'gs_distance': 0.00027928566105074755,
   'date': '2021-09-02T10:00:07.000Z',
   'gs_province': 'North Rhine-Westphalia',
   'gs_region': 'European Union',
   'gs_district': 'Overall',
   'gs_city': 'Krefeld',
   'gs_country': 'Germany',
   'gs_type': 'None',
   'gs_countrycode': 'DE',
   'gs_population': 227020,
   'composite': 77,

In [67]:
temp1[1][0]

{'hkey': 553,
 'gs_id': 'Q930205327',
 'gs_distance': 0.0005261024484226414,
 'date': '2021-09-02T10:00:07.000Z',
 'gs_province': 'Florida',
 'gs_region': 'North America',
 'gs_district': 'Northside',
 'gs_city': 'Jacksonville',
 'gs_country': 'United States',
 'gs_type': 'None',
 'gs_countrycode': 'US',
 'gs_population': 0,
 'composite': 68,
 'nightime': 63,
 'physical': 66,
 'women': 63,
 'theft': 65,
 'freedom': 79,
 'health': 62,
 'lgbtq': 73,
 'type': 'geosure',
 'status': True}