In [93]:
QUERY = connect.execute(sql_query)
hotel_df = pd.DataFrame()
a=[]
for row in QUERY:
    a.append(row)
#print(len(a))
hotel_df = pd.DataFrame(a)
df_col_names = QUERY.col_names
hotel_df.columns = df_col_names
hotel_df.shape

(469, 22)

In [94]:
hotel_df = hotel_df.fillna(0)
hotel_df = hotel_df.set_index('HOTEL_ID')
hotel_df.head()

,IS_WLAN,IS_CARPARK,IS_BATHROOMTUB,IS_LAUNDRY,IS_NONSMOKE,IS_BUSINESSHOTEL,IS_AIRPORTHOTEL,IS_APPARTMENTHOTEL,IS_EARLY_BREAKFAST,IS_FITNESS,...,IS_POOL,IS_HOTELBAR,IS_RESTAURANT,IS_AIRCON,IS_TRANSFER,NUMBER_DIST_CITYCENTER,NUMBER_DIST_AIRPORT,NUMBER_DIST_CENTRALSTATION,AVG_GOOGLE_RATING,AVG_HRS_RATING
HOTEL_ID,,,,,,,,,,,,,,,,,,,,,
62269,1,1,1,1,1,1,0,0,0,0,...,0,1,1,0,0,1,12,0,2.9,6.050
20482,1,1,0,1,1,1,0,0,0,1,...,0,1,1,1,0,1,12,0,3.9,7.345
421053,1,1,0,0,1,0,0,0,0,0,...,0,1,0,0,0,1,13,0,4.2,6.645
11424,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,13,0,0.0,0.000
588340,1,1,0,1,1,1,1,1,0,0,...,0,0,0,0,0,2,12,1,3.3,6.838

In [95]:
import pandas as pd
from rake_nltk import Rake
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity

# generating the cosine similarity matrix
cosine_sim = cosine_similarity(hotel_df.values, hotel_df.values)

In [96]:
indices = pd.Series(hotel_df.index)

def recommendations(hotel_id, cosine_sim = cosine_sim):
    recommended_hotels = []
    idx = indices[indices == hotel_id].index[0]
    
    # creating a Series with the similarity scores in descending order
    score_series = pd.Series(cosine_sim[idx]).sort_values(ascending = False)
    
    # getting the indexes of the 10 most similar hotels
    top_10_indexes = list(score_series.iloc[1:11].index)
    
    for i in top_10_indexes:
        recommended_hotels.append(list(hotel_df.index)[i])
    return recommended_hotels

In [97]:
reco = recommendations(83)

In [98]:
hotel_df[hotel_df.index.isin(reco)]

,IS_WLAN,IS_CARPARK,IS_BATHROOMTUB,IS_LAUNDRY,IS_NONSMOKE,IS_BUSINESSHOTEL,IS_AIRPORTHOTEL,IS_APPARTMENTHOTEL,IS_EARLY_BREAKFAST,IS_FITNESS,...,IS_POOL,IS_HOTELBAR,IS_RESTAURANT,IS_AIRCON,IS_TRANSFER,NUMBER_DIST_CITYCENTER,NUMBER_DIST_AIRPORT,NUMBER_DIST_CENTRALSTATION,AVG_GOOGLE_RATING,AVG_HRS_RATING
HOTEL_ID,,,,,,,,,,,,,,,,,,,,,
564290,1,1,0,1,1,0,0,0,0,1,...,0,1,0,1,0,1,20,3,5.0,8.919
5950,1,1,1,1,1,1,0,0,0,0,...,0,1,1,1,0,1,15,4,4.1,8.044
430902,1,1,0,1,1,0,0,1,0,0,...,0,0,0,0,0,1,14,2,2.9,5.857
146758,1,1,1,1,1,1,0,0,0,0,...,0,0,1,1,1,2,16,3,3.0,6.615
44392,1,1,0,0,1,0,0,0,0,0,...,0,1,1,0,0,1,14,2,2.1,4.969
768067,1,1,0,1,1,1,0,0,0,1,...,0,1,1,1,0,2,18,5,4.4,8.616
65723,1,1,0,1,1,0,0,0,0,0,...,0,1,1,1,0,0,14,2,3.7,6.717
163421,1,1,0,1,1,0,0,0,0,0,...,0,0,0,0,0,1,14,2,2.9,5.988
5946,1,1,1,1,1,0,0,0,0,0,...,0,1,1,0,0,1,15,3,3.1,6.399
11330,1,1,1,1,1,0,0,0,0,0,...,0,0,1,0,0,1,14,2,2.1,5.241

In [84]:
idx = indices[indices == 83].index[0]
    
# creating a Series with the similarity scores in descending order
score_series = pd.Series(cosine_sim[idx]).sort_values(ascending = False)
score_series[score_series.index.isin(reco)]

Series([], dtype: float64)

In [89]:
score_series.iloc[0:10]

240    1.000000
313    0.999809
8      0.992548
285    0.990912
80     0.989851
245    0.987218
335    0.987026
191    0.986691
190    0.986312
434    0.986171
dtype: float64