In [5]:
import pyexasol
import configparser
import pandas as pd


config = configparser.ConfigParser()
#Location of the ini file
config.read('C:\\Users\\svi02\\.spyder-py3\\ExasolPROD.ini')

dsn=config['exasolPROD']['dsn']
user=config['exasolPROD']['user']
pwd=config['exasolPROD']['pwd']
schema=config['exasolPROD']['schema']
# Exasol connection
connect = pyexasol.connect(dsn=dsn, user=user, password=pwd, schema=schema)

In [20]:
## Enter the query here 

exasol_df = connect.export_to_pandas(""" SELECT
        T.RFP_HOTEL_ID,
        D.MARKET_PLACE_CONTRACT_TYPE_NAME,
        MPHC.MP_HOTEL_CONTRACT_STATUS_NAME,
        TO_DATE(CURRENT_TIMESTAMP)                                         AS PFX_TIMESTAMP,
        EMP.CONTRACT_PERIOD_END,
        EMP.CONTRACT_PERIOD_START
    FROM (SELECT HOTEL_ID AS RFP_HOTEL_ID FROM DWHBIL.LKP_HOTEL) T
    JOIN DWHBIL.LKP_ERFP_MARKET_PLACE EMP ON EMP.HOTEL_ID = T.RFP_HOTEL_ID
    JOIN DWHBIL.LKP_MARKET_PLACE_CONTRACT_TYPE D  ON  EMP.MARKET_PLACE_CONTRACT_TYPE_ID  = D.MARKET_PLACE_CONTRACT_TYPE_ID
    LEFT JOIN  DWHBIL.LKP_MP_HOTEL_CONTRACT_STATUS MPHC ON MPHC.MP_HOTEL_CONTRACT_STATUS_ID = EMP.MP_HOTEL_CONTRACT_STATUS_ID
    """)
exasol_df.head()

,RFP_HOTEL_ID,MARKET_PLACE_CONTRACT_TYPE_NAME,MP_HOTEL_CONTRACT_STATUS_NAME,PFX_TIMESTAMP,CONTRACT_PERIOD_END,CONTRACT_PERIOD_START
0,657693,None,Invited,2021-03-22,NaN,NaN
1,945833,None,Invited,2021-03-22,NaN,NaN
2,53998,None,Invited,2021-03-22,NaN,NaN
3,409087,None,Invited,2021-03-22,NaN,NaN
4,961899,None,Solicited,2021-03-22,NaN,NaN

In [9]:
excel_df = pd.read_excel (r'O:\DE\Cologne\HS\Sourcing_Solutions\Special_Folder\Corporate_Sourcing\Sourcing Intelligence\06_Products\Reporting\Sourcing_E2E_RAW_DATA\Sourcing_Report_2021-03-22 09.04.xlsx', sheet_name='MP_Hotels')

,HOTEL_ID,HOTEL_NAME,HOTEL_CHAIN_ID,HOTEL_CHAIN_NAME,OFFICE_NAME,SALES_AREA,HOTEL_WORLD_REGION,CHAIN_CLUSTER,HOTEL_BRAND_ID,HOTEL_BRAND_NAME,...,IB_ACCEPTANCE_QUOTE,IB_AVERAGE_OFFER_RATE_EURO,IB_AVERAGE_TARGET_RATE_EURO,IB_AVERAGE_OFFER_RATE_VS_IB_AVG_TARGET_RATE,IB_AVERAGE_OFFER_RATE_VS_SMART_BID,IB_TOTAL_AVERAGE_OFFER_RATE_LRA_SHARE,IB_TOTAL_AVERAGE_OFFER_BREAKFAST_INCL_SHARE,IB_AVERAGE_OFFER_RATE_EURO_ACCEPTED,IB_AVERAGE_ACCEPTED_OFFER_RATE_LRA_SHARE,IB_AVERAGE_ACCEPTED_OFFER_RATE_BREAKFAST_INCL_SHARE
0,1,Savoy Berlin,237.0,WorldHotels,HS Cologne,Germany Berlin Dresden,Europe,Regional,237.0,WorldHotels,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,Berlin Plaza Am Kurfürstendamm,-1.0,individual,HS Cologne,Germany Berlin Dresden,Europe,Individual,-1.0,n.a.,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,Wyndham Excelsior,-1.0,individual,HS Cologne,Germany Berlin Dresden,Europe,Individual,-1.0,n.a.,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,9,"Hotel Birke, Ringhotel Kiel",63.0,Ringhotels e.V.,HS Cologne,Germany Hamburg,Europe,Local,63.0,Ringhotels e.V.,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,10,relexa Bellevue,100.0,relexa hotels GmbH,HS Cologne,Germany Hamburg,Europe,Local,100.0,relexa hotels GmbH,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN